// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class Expand
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject expandMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.Expand";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		expand("expand"),
		Expand_PriceAPI("PaymentGatewayStripe.Expand_PriceAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Expand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Expand(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject expandMendixObject)
	{
		if (expandMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, expandMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.expandMendixObject = expandMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Expand.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.Expand initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.Expand.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.Expand initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.Expand(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.Expand load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.Expand.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of expand
	 */
	public final java.lang.String getexpand()
	{
		return getexpand(getContext());
	}

	/**
	 * @param context
	 * @return value of expand
	 */
	public final java.lang.String getexpand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.expand.toString());
	}

	/**
	 * Set value of expand
	 * @param expand
	 */
	public final void setexpand(java.lang.String expand)
	{
		setexpand(getContext(), expand);
	}

	/**
	 * Set value of expand
	 * @param context
	 * @param expand
	 */
	public final void setexpand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expand)
	{
		getMendixObject().setValue(context, MemberNames.expand.toString(), expand);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Expand_PriceAPI
	 */
	public final paymentgatewaystripe.proxies.PriceAPI getExpand_PriceAPI() throws com.mendix.core.CoreException
	{
		return getExpand_PriceAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Expand_PriceAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PriceAPI getExpand_PriceAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PriceAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Expand_PriceAPI.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PriceAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Expand_PriceAPI
	 * @param expand_priceapi
	 */
	public final void setExpand_PriceAPI(paymentgatewaystripe.proxies.PriceAPI expand_priceapi)
	{
		setExpand_PriceAPI(getContext(), expand_priceapi);
	}

	/**
	 * Set value of Expand_PriceAPI
	 * @param context
	 * @param expand_priceapi
	 */
	public final void setExpand_PriceAPI(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PriceAPI expand_priceapi)
	{
		if (expand_priceapi == null) {
			getMendixObject().setValue(context, MemberNames.Expand_PriceAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Expand_PriceAPI.toString(), expand_priceapi.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return expandMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.Expand that = (paymentgatewaystripe.proxies.Expand) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
