// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class FinalizeInvoice_Customer_address
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_Customer_addressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.FinalizeInvoice_Customer_address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		City("City"),
		Country("Country"),
		Line1("Line1"),
		Postal_code("Postal_code"),
		State("State"),
		FinalizeInvoice_Customer_address_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Customer_address_FinalizeInvoice_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FinalizeInvoice_Customer_address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FinalizeInvoice_Customer_address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_Customer_addressMendixObject)
	{
		if (finalizeInvoice_Customer_addressMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, finalizeInvoice_Customer_addressMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.finalizeInvoice_Customer_addressMendixObject = finalizeInvoice_Customer_addressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FinalizeInvoice_Customer_address.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Line1
	 */
	public final java.lang.String getLine1()
	{
		return getLine1(getContext());
	}

	/**
	 * @param context
	 * @return value of Line1
	 */
	public final java.lang.String getLine1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Line1.toString());
	}

	/**
	 * Set value of Line1
	 * @param line1
	 */
	public final void setLine1(java.lang.String line1)
	{
		setLine1(getContext(), line1);
	}

	/**
	 * Set value of Line1
	 * @param context
	 * @param line1
	 */
	public final void setLine1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String line1)
	{
		getMendixObject().setValue(context, MemberNames.Line1.toString(), line1);
	}

	/**
	 * @return value of Postal_code
	 */
	public final java.lang.String getPostal_code()
	{
		return getPostal_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Postal_code
	 */
	public final java.lang.String getPostal_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Postal_code.toString());
	}

	/**
	 * Set value of Postal_code
	 * @param postal_code
	 */
	public final void setPostal_code(java.lang.String postal_code)
	{
		setPostal_code(getContext(), postal_code);
	}

	/**
	 * Set value of Postal_code
	 * @param context
	 * @param postal_code
	 */
	public final void setPostal_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postal_code)
	{
		getMendixObject().setValue(context, MemberNames.Postal_code.toString(), postal_code);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Root getFinalizeInvoice_Customer_address_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Customer_address_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Root getFinalizeInvoice_Customer_address_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @param finalizeinvoice_customer_address_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Root finalizeinvoice_customer_address_finalizeinvoice_root)
	{
		setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(getContext(), finalizeinvoice_customer_address_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_customer_address_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Root finalizeinvoice_customer_address_finalizeinvoice_root)
	{
		if (finalizeinvoice_customer_address_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString(), finalizeinvoice_customer_address_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return finalizeInvoice_Customer_addressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address that = (paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
