// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class FinalizeInvoice_Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_RootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.FinalizeInvoice_Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Account_country("Account_country"),
		Account_name("Account_name"),
		Amount_due("Amount_due"),
		Amount_paid("Amount_paid"),
		Amount_remaining("Amount_remaining"),
		Attempt_count("Attempt_count"),
		Attempted("Attempted"),
		Auto_advance("Auto_advance"),
		Billing_reason("Billing_reason"),
		Collection_method("Collection_method"),
		Created("Created"),
		Currency("Currency"),
		Customer("Customer"),
		Customer_email("Customer_email"),
		Customer_name("Customer_name"),
		Customer_tax_exempt("Customer_tax_exempt"),
		Ending_balance("Ending_balance"),
		Hosted_invoice_url("Hosted_invoice_url"),
		Invoice_pdf("Invoice_pdf"),
		Livemode("Livemode"),
		Number("Number"),
		Paid("Paid"),
		Paid_out_of_band("Paid_out_of_band"),
		Payment_intent("Payment_intent"),
		Period_end("Period_end"),
		Period_start("Period_start"),
		Post_payment_credit_notes_amount("Post_payment_credit_notes_amount"),
		Pre_payment_credit_notes_amount("Pre_payment_credit_notes_amount"),
		Starting_balance("Starting_balance"),
		Status("Status"),
		Subtotal("Subtotal"),
		Subtotal_excluding_tax("Subtotal_excluding_tax"),
		Total("Total"),
		Total_excluding_tax("Total_excluding_tax"),
		FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root"),
		FinalizeInvoice_Customer_address_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Customer_address_FinalizeInvoice_Root"),
		FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root"),
		FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root"),
		FinalizeInvoice_Discounts_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Discounts_FinalizeInvoice_Root"),
		FinalizeInvoice_Lines_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Lines_FinalizeInvoice_Root"),
		FinalizeInvoice_Metadata_3_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Metadata_3_FinalizeInvoice_Root"),
		FinalizeInvoice_Payment_settings_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Payment_settings_FinalizeInvoice_Root"),
		FinalizeInvoice_Status_transitions_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Status_transitions_FinalizeInvoice_Root"),
		FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root"),
		FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_RootMendixObject)
	{
		if (finalizeInvoice_RootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, finalizeInvoice_RootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.finalizeInvoice_RootMendixObject = finalizeInvoice_RootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FinalizeInvoice_Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.FinalizeInvoice_Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.FinalizeInvoice_Root(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.FinalizeInvoice_Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.FinalizeInvoice_Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Account_country
	 */
	public final java.lang.String getAccount_country()
	{
		return getAccount_country(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_country
	 */
	public final java.lang.String getAccount_country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account_country.toString());
	}

	/**
	 * Set value of Account_country
	 * @param account_country
	 */
	public final void setAccount_country(java.lang.String account_country)
	{
		setAccount_country(getContext(), account_country);
	}

	/**
	 * Set value of Account_country
	 * @param context
	 * @param account_country
	 */
	public final void setAccount_country(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account_country)
	{
		getMendixObject().setValue(context, MemberNames.Account_country.toString(), account_country);
	}

	/**
	 * @return value of Account_name
	 */
	public final java.lang.String getAccount_name()
	{
		return getAccount_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_name
	 */
	public final java.lang.String getAccount_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account_name.toString());
	}

	/**
	 * Set value of Account_name
	 * @param account_name
	 */
	public final void setAccount_name(java.lang.String account_name)
	{
		setAccount_name(getContext(), account_name);
	}

	/**
	 * Set value of Account_name
	 * @param context
	 * @param account_name
	 */
	public final void setAccount_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account_name)
	{
		getMendixObject().setValue(context, MemberNames.Account_name.toString(), account_name);
	}

	/**
	 * @return value of Amount_due
	 */
	public final java.lang.Integer getAmount_due()
	{
		return getAmount_due(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_due
	 */
	public final java.lang.Integer getAmount_due(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_due.toString());
	}

	/**
	 * Set value of Amount_due
	 * @param amount_due
	 */
	public final void setAmount_due(java.lang.Integer amount_due)
	{
		setAmount_due(getContext(), amount_due);
	}

	/**
	 * Set value of Amount_due
	 * @param context
	 * @param amount_due
	 */
	public final void setAmount_due(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_due)
	{
		getMendixObject().setValue(context, MemberNames.Amount_due.toString(), amount_due);
	}

	/**
	 * @return value of Amount_paid
	 */
	public final java.lang.Integer getAmount_paid()
	{
		return getAmount_paid(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_paid
	 */
	public final java.lang.Integer getAmount_paid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_paid.toString());
	}

	/**
	 * Set value of Amount_paid
	 * @param amount_paid
	 */
	public final void setAmount_paid(java.lang.Integer amount_paid)
	{
		setAmount_paid(getContext(), amount_paid);
	}

	/**
	 * Set value of Amount_paid
	 * @param context
	 * @param amount_paid
	 */
	public final void setAmount_paid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_paid)
	{
		getMendixObject().setValue(context, MemberNames.Amount_paid.toString(), amount_paid);
	}

	/**
	 * @return value of Amount_remaining
	 */
	public final java.lang.Integer getAmount_remaining()
	{
		return getAmount_remaining(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_remaining
	 */
	public final java.lang.Integer getAmount_remaining(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_remaining.toString());
	}

	/**
	 * Set value of Amount_remaining
	 * @param amount_remaining
	 */
	public final void setAmount_remaining(java.lang.Integer amount_remaining)
	{
		setAmount_remaining(getContext(), amount_remaining);
	}

	/**
	 * Set value of Amount_remaining
	 * @param context
	 * @param amount_remaining
	 */
	public final void setAmount_remaining(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_remaining)
	{
		getMendixObject().setValue(context, MemberNames.Amount_remaining.toString(), amount_remaining);
	}

	/**
	 * @return value of Attempt_count
	 */
	public final java.lang.Integer getAttempt_count()
	{
		return getAttempt_count(getContext());
	}

	/**
	 * @param context
	 * @return value of Attempt_count
	 */
	public final java.lang.Integer getAttempt_count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Attempt_count.toString());
	}

	/**
	 * Set value of Attempt_count
	 * @param attempt_count
	 */
	public final void setAttempt_count(java.lang.Integer attempt_count)
	{
		setAttempt_count(getContext(), attempt_count);
	}

	/**
	 * Set value of Attempt_count
	 * @param context
	 * @param attempt_count
	 */
	public final void setAttempt_count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attempt_count)
	{
		getMendixObject().setValue(context, MemberNames.Attempt_count.toString(), attempt_count);
	}

	/**
	 * @return value of Attempted
	 */
	public final java.lang.Boolean getAttempted()
	{
		return getAttempted(getContext());
	}

	/**
	 * @param context
	 * @return value of Attempted
	 */
	public final java.lang.Boolean getAttempted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Attempted.toString());
	}

	/**
	 * Set value of Attempted
	 * @param attempted
	 */
	public final void setAttempted(java.lang.Boolean attempted)
	{
		setAttempted(getContext(), attempted);
	}

	/**
	 * Set value of Attempted
	 * @param context
	 * @param attempted
	 */
	public final void setAttempted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attempted)
	{
		getMendixObject().setValue(context, MemberNames.Attempted.toString(), attempted);
	}

	/**
	 * @return value of Auto_advance
	 */
	public final java.lang.Boolean getAuto_advance()
	{
		return getAuto_advance(getContext());
	}

	/**
	 * @param context
	 * @return value of Auto_advance
	 */
	public final java.lang.Boolean getAuto_advance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Auto_advance.toString());
	}

	/**
	 * Set value of Auto_advance
	 * @param auto_advance
	 */
	public final void setAuto_advance(java.lang.Boolean auto_advance)
	{
		setAuto_advance(getContext(), auto_advance);
	}

	/**
	 * Set value of Auto_advance
	 * @param context
	 * @param auto_advance
	 */
	public final void setAuto_advance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean auto_advance)
	{
		getMendixObject().setValue(context, MemberNames.Auto_advance.toString(), auto_advance);
	}

	/**
	 * @return value of Billing_reason
	 */
	public final java.lang.String getBilling_reason()
	{
		return getBilling_reason(getContext());
	}

	/**
	 * @param context
	 * @return value of Billing_reason
	 */
	public final java.lang.String getBilling_reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Billing_reason.toString());
	}

	/**
	 * Set value of Billing_reason
	 * @param billing_reason
	 */
	public final void setBilling_reason(java.lang.String billing_reason)
	{
		setBilling_reason(getContext(), billing_reason);
	}

	/**
	 * Set value of Billing_reason
	 * @param context
	 * @param billing_reason
	 */
	public final void setBilling_reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billing_reason)
	{
		getMendixObject().setValue(context, MemberNames.Billing_reason.toString(), billing_reason);
	}

	/**
	 * @return value of Collection_method
	 */
	public final java.lang.String getCollection_method()
	{
		return getCollection_method(getContext());
	}

	/**
	 * @param context
	 * @return value of Collection_method
	 */
	public final java.lang.String getCollection_method(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Collection_method.toString());
	}

	/**
	 * Set value of Collection_method
	 * @param collection_method
	 */
	public final void setCollection_method(java.lang.String collection_method)
	{
		setCollection_method(getContext(), collection_method);
	}

	/**
	 * Set value of Collection_method
	 * @param context
	 * @param collection_method
	 */
	public final void setCollection_method(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String collection_method)
	{
		getMendixObject().setValue(context, MemberNames.Collection_method.toString(), collection_method);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer()
	{
		return getCustomer(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer.toString());
	}

	/**
	 * Set value of Customer
	 * @param customer
	 */
	public final void setCustomer(java.lang.String customer)
	{
		setCustomer(getContext(), customer);
	}

	/**
	 * Set value of Customer
	 * @param context
	 * @param customer
	 */
	public final void setCustomer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer)
	{
		getMendixObject().setValue(context, MemberNames.Customer.toString(), customer);
	}

	/**
	 * @return value of Customer_email
	 */
	public final java.lang.String getCustomer_email()
	{
		return getCustomer_email(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_email
	 */
	public final java.lang.String getCustomer_email(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_email.toString());
	}

	/**
	 * Set value of Customer_email
	 * @param customer_email
	 */
	public final void setCustomer_email(java.lang.String customer_email)
	{
		setCustomer_email(getContext(), customer_email);
	}

	/**
	 * Set value of Customer_email
	 * @param context
	 * @param customer_email
	 */
	public final void setCustomer_email(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_email)
	{
		getMendixObject().setValue(context, MemberNames.Customer_email.toString(), customer_email);
	}

	/**
	 * @return value of Customer_name
	 */
	public final java.lang.String getCustomer_name()
	{
		return getCustomer_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_name
	 */
	public final java.lang.String getCustomer_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_name.toString());
	}

	/**
	 * Set value of Customer_name
	 * @param customer_name
	 */
	public final void setCustomer_name(java.lang.String customer_name)
	{
		setCustomer_name(getContext(), customer_name);
	}

	/**
	 * Set value of Customer_name
	 * @param context
	 * @param customer_name
	 */
	public final void setCustomer_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_name)
	{
		getMendixObject().setValue(context, MemberNames.Customer_name.toString(), customer_name);
	}

	/**
	 * @return value of Customer_tax_exempt
	 */
	public final java.lang.String getCustomer_tax_exempt()
	{
		return getCustomer_tax_exempt(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_tax_exempt
	 */
	public final java.lang.String getCustomer_tax_exempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_tax_exempt.toString());
	}

	/**
	 * Set value of Customer_tax_exempt
	 * @param customer_tax_exempt
	 */
	public final void setCustomer_tax_exempt(java.lang.String customer_tax_exempt)
	{
		setCustomer_tax_exempt(getContext(), customer_tax_exempt);
	}

	/**
	 * Set value of Customer_tax_exempt
	 * @param context
	 * @param customer_tax_exempt
	 */
	public final void setCustomer_tax_exempt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_tax_exempt)
	{
		getMendixObject().setValue(context, MemberNames.Customer_tax_exempt.toString(), customer_tax_exempt);
	}

	/**
	 * @return value of Ending_balance
	 */
	public final java.lang.Integer getEnding_balance()
	{
		return getEnding_balance(getContext());
	}

	/**
	 * @param context
	 * @return value of Ending_balance
	 */
	public final java.lang.Integer getEnding_balance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ending_balance.toString());
	}

	/**
	 * Set value of Ending_balance
	 * @param ending_balance
	 */
	public final void setEnding_balance(java.lang.Integer ending_balance)
	{
		setEnding_balance(getContext(), ending_balance);
	}

	/**
	 * Set value of Ending_balance
	 * @param context
	 * @param ending_balance
	 */
	public final void setEnding_balance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ending_balance)
	{
		getMendixObject().setValue(context, MemberNames.Ending_balance.toString(), ending_balance);
	}

	/**
	 * @return value of Hosted_invoice_url
	 */
	public final java.lang.String getHosted_invoice_url()
	{
		return getHosted_invoice_url(getContext());
	}

	/**
	 * @param context
	 * @return value of Hosted_invoice_url
	 */
	public final java.lang.String getHosted_invoice_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hosted_invoice_url.toString());
	}

	/**
	 * Set value of Hosted_invoice_url
	 * @param hosted_invoice_url
	 */
	public final void setHosted_invoice_url(java.lang.String hosted_invoice_url)
	{
		setHosted_invoice_url(getContext(), hosted_invoice_url);
	}

	/**
	 * Set value of Hosted_invoice_url
	 * @param context
	 * @param hosted_invoice_url
	 */
	public final void setHosted_invoice_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hosted_invoice_url)
	{
		getMendixObject().setValue(context, MemberNames.Hosted_invoice_url.toString(), hosted_invoice_url);
	}

	/**
	 * @return value of Invoice_pdf
	 */
	public final java.lang.String getInvoice_pdf()
	{
		return getInvoice_pdf(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_pdf
	 */
	public final java.lang.String getInvoice_pdf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Invoice_pdf.toString());
	}

	/**
	 * Set value of Invoice_pdf
	 * @param invoice_pdf
	 */
	public final void setInvoice_pdf(java.lang.String invoice_pdf)
	{
		setInvoice_pdf(getContext(), invoice_pdf);
	}

	/**
	 * Set value of Invoice_pdf
	 * @param context
	 * @param invoice_pdf
	 */
	public final void setInvoice_pdf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String invoice_pdf)
	{
		getMendixObject().setValue(context, MemberNames.Invoice_pdf.toString(), invoice_pdf);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.String getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.String getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.String number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Paid
	 */
	public final java.lang.Boolean getPaid()
	{
		return getPaid(getContext());
	}

	/**
	 * @param context
	 * @return value of Paid
	 */
	public final java.lang.Boolean getPaid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Paid.toString());
	}

	/**
	 * Set value of Paid
	 * @param paid
	 */
	public final void setPaid(java.lang.Boolean paid)
	{
		setPaid(getContext(), paid);
	}

	/**
	 * Set value of Paid
	 * @param context
	 * @param paid
	 */
	public final void setPaid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean paid)
	{
		getMendixObject().setValue(context, MemberNames.Paid.toString(), paid);
	}

	/**
	 * @return value of Paid_out_of_band
	 */
	public final java.lang.Boolean getPaid_out_of_band()
	{
		return getPaid_out_of_band(getContext());
	}

	/**
	 * @param context
	 * @return value of Paid_out_of_band
	 */
	public final java.lang.Boolean getPaid_out_of_band(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Paid_out_of_band.toString());
	}

	/**
	 * Set value of Paid_out_of_band
	 * @param paid_out_of_band
	 */
	public final void setPaid_out_of_band(java.lang.Boolean paid_out_of_band)
	{
		setPaid_out_of_band(getContext(), paid_out_of_band);
	}

	/**
	 * Set value of Paid_out_of_band
	 * @param context
	 * @param paid_out_of_band
	 */
	public final void setPaid_out_of_band(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean paid_out_of_band)
	{
		getMendixObject().setValue(context, MemberNames.Paid_out_of_band.toString(), paid_out_of_band);
	}

	/**
	 * @return value of Payment_intent
	 */
	public final java.lang.String getPayment_intent()
	{
		return getPayment_intent(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_intent
	 */
	public final java.lang.String getPayment_intent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payment_intent.toString());
	}

	/**
	 * Set value of Payment_intent
	 * @param payment_intent
	 */
	public final void setPayment_intent(java.lang.String payment_intent)
	{
		setPayment_intent(getContext(), payment_intent);
	}

	/**
	 * Set value of Payment_intent
	 * @param context
	 * @param payment_intent
	 */
	public final void setPayment_intent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payment_intent)
	{
		getMendixObject().setValue(context, MemberNames.Payment_intent.toString(), payment_intent);
	}

	/**
	 * @return value of Period_end
	 */
	public final java.lang.Integer getPeriod_end()
	{
		return getPeriod_end(getContext());
	}

	/**
	 * @param context
	 * @return value of Period_end
	 */
	public final java.lang.Integer getPeriod_end(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Period_end.toString());
	}

	/**
	 * Set value of Period_end
	 * @param period_end
	 */
	public final void setPeriod_end(java.lang.Integer period_end)
	{
		setPeriod_end(getContext(), period_end);
	}

	/**
	 * Set value of Period_end
	 * @param context
	 * @param period_end
	 */
	public final void setPeriod_end(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer period_end)
	{
		getMendixObject().setValue(context, MemberNames.Period_end.toString(), period_end);
	}

	/**
	 * @return value of Period_start
	 */
	public final java.lang.Integer getPeriod_start()
	{
		return getPeriod_start(getContext());
	}

	/**
	 * @param context
	 * @return value of Period_start
	 */
	public final java.lang.Integer getPeriod_start(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Period_start.toString());
	}

	/**
	 * Set value of Period_start
	 * @param period_start
	 */
	public final void setPeriod_start(java.lang.Integer period_start)
	{
		setPeriod_start(getContext(), period_start);
	}

	/**
	 * Set value of Period_start
	 * @param context
	 * @param period_start
	 */
	public final void setPeriod_start(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer period_start)
	{
		getMendixObject().setValue(context, MemberNames.Period_start.toString(), period_start);
	}

	/**
	 * @return value of Post_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPost_payment_credit_notes_amount()
	{
		return getPost_payment_credit_notes_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Post_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPost_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Post_payment_credit_notes_amount.toString());
	}

	/**
	 * Set value of Post_payment_credit_notes_amount
	 * @param post_payment_credit_notes_amount
	 */
	public final void setPost_payment_credit_notes_amount(java.lang.Integer post_payment_credit_notes_amount)
	{
		setPost_payment_credit_notes_amount(getContext(), post_payment_credit_notes_amount);
	}

	/**
	 * Set value of Post_payment_credit_notes_amount
	 * @param context
	 * @param post_payment_credit_notes_amount
	 */
	public final void setPost_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer post_payment_credit_notes_amount)
	{
		getMendixObject().setValue(context, MemberNames.Post_payment_credit_notes_amount.toString(), post_payment_credit_notes_amount);
	}

	/**
	 * @return value of Pre_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPre_payment_credit_notes_amount()
	{
		return getPre_payment_credit_notes_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Pre_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPre_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pre_payment_credit_notes_amount.toString());
	}

	/**
	 * Set value of Pre_payment_credit_notes_amount
	 * @param pre_payment_credit_notes_amount
	 */
	public final void setPre_payment_credit_notes_amount(java.lang.Integer pre_payment_credit_notes_amount)
	{
		setPre_payment_credit_notes_amount(getContext(), pre_payment_credit_notes_amount);
	}

	/**
	 * Set value of Pre_payment_credit_notes_amount
	 * @param context
	 * @param pre_payment_credit_notes_amount
	 */
	public final void setPre_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pre_payment_credit_notes_amount)
	{
		getMendixObject().setValue(context, MemberNames.Pre_payment_credit_notes_amount.toString(), pre_payment_credit_notes_amount);
	}

	/**
	 * @return value of Starting_balance
	 */
	public final java.lang.Integer getStarting_balance()
	{
		return getStarting_balance(getContext());
	}

	/**
	 * @param context
	 * @return value of Starting_balance
	 */
	public final java.lang.Integer getStarting_balance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Starting_balance.toString());
	}

	/**
	 * Set value of Starting_balance
	 * @param starting_balance
	 */
	public final void setStarting_balance(java.lang.Integer starting_balance)
	{
		setStarting_balance(getContext(), starting_balance);
	}

	/**
	 * Set value of Starting_balance
	 * @param context
	 * @param starting_balance
	 */
	public final void setStarting_balance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer starting_balance)
	{
		getMendixObject().setValue(context, MemberNames.Starting_balance.toString(), starting_balance);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Subtotal
	 */
	public final java.lang.Integer getSubtotal()
	{
		return getSubtotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Subtotal
	 */
	public final java.lang.Integer getSubtotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Subtotal.toString());
	}

	/**
	 * Set value of Subtotal
	 * @param subtotal
	 */
	public final void setSubtotal(java.lang.Integer subtotal)
	{
		setSubtotal(getContext(), subtotal);
	}

	/**
	 * Set value of Subtotal
	 * @param context
	 * @param subtotal
	 */
	public final void setSubtotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer subtotal)
	{
		getMendixObject().setValue(context, MemberNames.Subtotal.toString(), subtotal);
	}

	/**
	 * @return value of Subtotal_excluding_tax
	 */
	public final java.lang.Integer getSubtotal_excluding_tax()
	{
		return getSubtotal_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Subtotal_excluding_tax
	 */
	public final java.lang.Integer getSubtotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Subtotal_excluding_tax.toString());
	}

	/**
	 * Set value of Subtotal_excluding_tax
	 * @param subtotal_excluding_tax
	 */
	public final void setSubtotal_excluding_tax(java.lang.Integer subtotal_excluding_tax)
	{
		setSubtotal_excluding_tax(getContext(), subtotal_excluding_tax);
	}

	/**
	 * Set value of Subtotal_excluding_tax
	 * @param context
	 * @param subtotal_excluding_tax
	 */
	public final void setSubtotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer subtotal_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Subtotal_excluding_tax.toString(), subtotal_excluding_tax);
	}

	/**
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal()
	{
		return getTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total.toString());
	}

	/**
	 * Set value of Total
	 * @param total
	 */
	public final void setTotal(java.lang.Integer total)
	{
		setTotal(getContext(), total);
	}

	/**
	 * Set value of Total
	 * @param context
	 * @param total
	 */
	public final void setTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total)
	{
		getMendixObject().setValue(context, MemberNames.Total.toString(), total);
	}

	/**
	 * @return value of Total_excluding_tax
	 */
	public final java.lang.Integer getTotal_excluding_tax()
	{
		return getTotal_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_excluding_tax
	 */
	public final java.lang.Integer getTotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total_excluding_tax.toString());
	}

	/**
	 * Set value of Total_excluding_tax
	 * @param total_excluding_tax
	 */
	public final void setTotal_excluding_tax(java.lang.Integer total_excluding_tax)
	{
		setTotal_excluding_tax(getContext(), total_excluding_tax);
	}

	/**
	 * Set value of Total_excluding_tax
	 * @param context
	 * @param total_excluding_tax
	 */
	public final void setTotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Total_excluding_tax.toString(), total_excluding_tax);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax getFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax getFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root
	 * @param finalizeinvoice_automatic_tax_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax finalizeinvoice_automatic_tax_finalizeinvoice_root)
	{
		setFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root(getContext(), finalizeinvoice_automatic_tax_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_automatic_tax_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Automatic_tax_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Automatic_tax finalizeinvoice_automatic_tax_finalizeinvoice_root)
	{
		if (finalizeinvoice_automatic_tax_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Automatic_tax_FinalizeInvoice_Root.toString(), finalizeinvoice_automatic_tax_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address getFinalizeInvoice_Customer_address_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Customer_address_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address getFinalizeInvoice_Customer_address_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @param finalizeinvoice_customer_address_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address finalizeinvoice_customer_address_finalizeinvoice_root)
	{
		setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(getContext(), finalizeinvoice_customer_address_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Customer_address_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_customer_address_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_address_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Customer_address finalizeinvoice_customer_address_finalizeinvoice_root)
	{
		if (finalizeinvoice_customer_address_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_address_FinalizeInvoice_Root.toString(), finalizeinvoice_customer_address_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids getFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids getFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root
	 * @param finalizeinvoice_customer_tax_ids_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids finalizeinvoice_customer_tax_ids_finalizeinvoice_root)
	{
		setFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root(getContext(), finalizeinvoice_customer_tax_ids_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_customer_tax_ids_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Customer_tax_ids finalizeinvoice_customer_tax_ids_finalizeinvoice_root)
	{
		if (finalizeinvoice_customer_tax_ids_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Customer_tax_ids_FinalizeInvoice_Root.toString(), finalizeinvoice_customer_tax_ids_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates getFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates getFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root
	 * @param finalizeinvoice_default_tax_rates_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates finalizeinvoice_default_tax_rates_finalizeinvoice_root)
	{
		setFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root(getContext(), finalizeinvoice_default_tax_rates_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_default_tax_rates_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Default_tax_rates finalizeinvoice_default_tax_rates_finalizeinvoice_root)
	{
		if (finalizeinvoice_default_tax_rates_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Default_tax_rates_FinalizeInvoice_Root.toString(), finalizeinvoice_default_tax_rates_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Discounts_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Discounts getFinalizeInvoice_Discounts_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Discounts_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Discounts_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Discounts getFinalizeInvoice_Discounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Discounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Discounts_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Discounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Discounts_FinalizeInvoice_Root
	 * @param finalizeinvoice_discounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Discounts_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Discounts finalizeinvoice_discounts_finalizeinvoice_root)
	{
		setFinalizeInvoice_Discounts_FinalizeInvoice_Root(getContext(), finalizeinvoice_discounts_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Discounts_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_discounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Discounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Discounts finalizeinvoice_discounts_finalizeinvoice_root)
	{
		if (finalizeinvoice_discounts_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Discounts_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Discounts_FinalizeInvoice_Root.toString(), finalizeinvoice_discounts_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Lines getFinalizeInvoice_Lines_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Lines_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Lines getFinalizeInvoice_Lines_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Lines result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Lines.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @param finalizeinvoice_lines_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Lines_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Lines finalizeinvoice_lines_finalizeinvoice_root)
	{
		setFinalizeInvoice_Lines_FinalizeInvoice_Root(getContext(), finalizeinvoice_lines_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_lines_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Lines_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Lines finalizeinvoice_lines_finalizeinvoice_root)
	{
		if (finalizeinvoice_lines_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString(), finalizeinvoice_lines_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Metadata_3_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3 getFinalizeInvoice_Metadata_3_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Metadata_3_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Metadata_3_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3 getFinalizeInvoice_Metadata_3_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Metadata_3_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Metadata_3_FinalizeInvoice_Root
	 * @param finalizeinvoice_metadata_3_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Metadata_3_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3 finalizeinvoice_metadata_3_finalizeinvoice_root)
	{
		setFinalizeInvoice_Metadata_3_FinalizeInvoice_Root(getContext(), finalizeinvoice_metadata_3_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Metadata_3_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_metadata_3_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Metadata_3_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Metadata_3 finalizeinvoice_metadata_3_finalizeinvoice_root)
	{
		if (finalizeinvoice_metadata_3_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Metadata_3_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Metadata_3_FinalizeInvoice_Root.toString(), finalizeinvoice_metadata_3_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Payment_settings_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings getFinalizeInvoice_Payment_settings_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Payment_settings_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Payment_settings_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings getFinalizeInvoice_Payment_settings_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Payment_settings_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Payment_settings_FinalizeInvoice_Root
	 * @param finalizeinvoice_payment_settings_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Payment_settings_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings finalizeinvoice_payment_settings_finalizeinvoice_root)
	{
		setFinalizeInvoice_Payment_settings_FinalizeInvoice_Root(getContext(), finalizeinvoice_payment_settings_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Payment_settings_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_payment_settings_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Payment_settings_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Payment_settings finalizeinvoice_payment_settings_finalizeinvoice_root)
	{
		if (finalizeinvoice_payment_settings_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Payment_settings_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Payment_settings_FinalizeInvoice_Root.toString(), finalizeinvoice_payment_settings_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Status_transitions_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions getFinalizeInvoice_Status_transitions_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Status_transitions_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Status_transitions_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions getFinalizeInvoice_Status_transitions_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Status_transitions_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Status_transitions_FinalizeInvoice_Root
	 * @param finalizeinvoice_status_transitions_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Status_transitions_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions finalizeinvoice_status_transitions_finalizeinvoice_root)
	{
		setFinalizeInvoice_Status_transitions_FinalizeInvoice_Root(getContext(), finalizeinvoice_status_transitions_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Status_transitions_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_status_transitions_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Status_transitions_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Status_transitions finalizeinvoice_status_transitions_finalizeinvoice_root)
	{
		if (finalizeinvoice_status_transitions_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Status_transitions_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Status_transitions_FinalizeInvoice_Root.toString(), finalizeinvoice_status_transitions_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts getFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts getFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root
	 * @param finalizeinvoice_total_discount_amounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts finalizeinvoice_total_discount_amounts_finalizeinvoice_root)
	{
		setFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root(getContext(), finalizeinvoice_total_discount_amounts_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_total_discount_amounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Total_discount_amounts finalizeinvoice_total_discount_amounts_finalizeinvoice_root)
	{
		if (finalizeinvoice_total_discount_amounts_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Total_discount_amounts_FinalizeInvoice_Root.toString(), finalizeinvoice_total_discount_amounts_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts getFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts getFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root
	 * @param finalizeinvoice_total_tax_amounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts finalizeinvoice_total_tax_amounts_finalizeinvoice_root)
	{
		setFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root(getContext(), finalizeinvoice_total_tax_amounts_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_total_tax_amounts_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Total_tax_amounts finalizeinvoice_total_tax_amounts_finalizeinvoice_root)
	{
		if (finalizeinvoice_total_tax_amounts_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Total_tax_amounts_FinalizeInvoice_Root.toString(), finalizeinvoice_total_tax_amounts_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return finalizeInvoice_RootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.FinalizeInvoice_Root that = (paymentgatewaystripe.proxies.FinalizeInvoice_Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
