// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class FinalizeInvoice_Lines
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_LinesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.FinalizeInvoice_Lines";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_object("_object"),
		Has_more("Has_more"),
		Total_count("Total_count"),
		Url("Url"),
		FinalizeInvoice_Lines_FinalizeInvoice_Root("PaymentGatewayStripe.FinalizeInvoice_Lines_FinalizeInvoice_Root"),
		FinalizeInvoice_Data_FinalizeInvoice_Lines("PaymentGatewayStripe.FinalizeInvoice_Data_FinalizeInvoice_Lines");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FinalizeInvoice_Lines(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FinalizeInvoice_Lines(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_LinesMendixObject)
	{
		if (finalizeInvoice_LinesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, finalizeInvoice_LinesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.finalizeInvoice_LinesMendixObject = finalizeInvoice_LinesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FinalizeInvoice_Lines.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Lines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.FinalizeInvoice_Lines.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.FinalizeInvoice_Lines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.FinalizeInvoice_Lines(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.FinalizeInvoice_Lines load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.FinalizeInvoice_Lines.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Has_more
	 */
	public final java.lang.Boolean getHas_more()
	{
		return getHas_more(getContext());
	}

	/**
	 * @param context
	 * @return value of Has_more
	 */
	public final java.lang.Boolean getHas_more(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Has_more.toString());
	}

	/**
	 * Set value of Has_more
	 * @param has_more
	 */
	public final void setHas_more(java.lang.Boolean has_more)
	{
		setHas_more(getContext(), has_more);
	}

	/**
	 * Set value of Has_more
	 * @param context
	 * @param has_more
	 */
	public final void setHas_more(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean has_more)
	{
		getMendixObject().setValue(context, MemberNames.Has_more.toString(), has_more);
	}

	/**
	 * @return value of Total_count
	 */
	public final java.lang.Integer getTotal_count()
	{
		return getTotal_count(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_count
	 */
	public final java.lang.Integer getTotal_count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total_count.toString());
	}

	/**
	 * Set value of Total_count
	 * @param total_count
	 */
	public final void setTotal_count(java.lang.Integer total_count)
	{
		setTotal_count(getContext(), total_count);
	}

	/**
	 * Set value of Total_count
	 * @param context
	 * @param total_count
	 */
	public final void setTotal_count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total_count)
	{
		getMendixObject().setValue(context, MemberNames.Total_count.toString(), total_count);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Root getFinalizeInvoice_Lines_FinalizeInvoice_Root() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Lines_FinalizeInvoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Root getFinalizeInvoice_Lines_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @param finalizeinvoice_lines_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Lines_FinalizeInvoice_Root(paymentgatewaystripe.proxies.FinalizeInvoice_Root finalizeinvoice_lines_finalizeinvoice_root)
	{
		setFinalizeInvoice_Lines_FinalizeInvoice_Root(getContext(), finalizeinvoice_lines_finalizeinvoice_root);
	}

	/**
	 * Set value of FinalizeInvoice_Lines_FinalizeInvoice_Root
	 * @param context
	 * @param finalizeinvoice_lines_finalizeinvoice_root
	 */
	public final void setFinalizeInvoice_Lines_FinalizeInvoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Root finalizeinvoice_lines_finalizeinvoice_root)
	{
		if (finalizeinvoice_lines_finalizeinvoice_root == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Lines_FinalizeInvoice_Root.toString(), finalizeinvoice_lines_finalizeinvoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Data_FinalizeInvoice_Lines
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Data getFinalizeInvoice_Data_FinalizeInvoice_Lines() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Data_FinalizeInvoice_Lines(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Data_FinalizeInvoice_Lines
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Data getFinalizeInvoice_Data_FinalizeInvoice_Lines(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Data_FinalizeInvoice_Lines.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Data.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Data_FinalizeInvoice_Lines
	 * @param finalizeinvoice_data_finalizeinvoice_lines
	 */
	public final void setFinalizeInvoice_Data_FinalizeInvoice_Lines(paymentgatewaystripe.proxies.FinalizeInvoice_Data finalizeinvoice_data_finalizeinvoice_lines)
	{
		setFinalizeInvoice_Data_FinalizeInvoice_Lines(getContext(), finalizeinvoice_data_finalizeinvoice_lines);
	}

	/**
	 * Set value of FinalizeInvoice_Data_FinalizeInvoice_Lines
	 * @param context
	 * @param finalizeinvoice_data_finalizeinvoice_lines
	 */
	public final void setFinalizeInvoice_Data_FinalizeInvoice_Lines(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Data finalizeinvoice_data_finalizeinvoice_lines)
	{
		if (finalizeinvoice_data_finalizeinvoice_lines == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Data_FinalizeInvoice_Lines.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Data_FinalizeInvoice_Lines.toString(), finalizeinvoice_data_finalizeinvoice_lines.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return finalizeInvoice_LinesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.FinalizeInvoice_Lines that = (paymentgatewaystripe.proxies.FinalizeInvoice_Lines) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
