// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class FinalizeInvoice_JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_JsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.FinalizeInvoice_JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Amount("Amount"),
		Amount_excluding_tax("Amount_excluding_tax"),
		Currency("Currency"),
		Description("Description"),
		Discountable("Discountable"),
		Invoice_item("Invoice_item"),
		Livemode("Livemode"),
		Proration("Proration"),
		Quantity("Quantity"),
		_type("_type"),
		Unit_amount_excluding_tax("Unit_amount_excluding_tax"),
		FinalizeInvoice_JsonObject_FinalizeInvoice_Data("PaymentGatewayStripe.FinalizeInvoice_JsonObject_FinalizeInvoice_Data"),
		FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject"),
		FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Period_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Period_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Price_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Price_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject"),
		FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject("PaymentGatewayStripe.FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject finalizeInvoice_JsonObjectMendixObject)
	{
		if (finalizeInvoice_JsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, finalizeInvoice_JsonObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.finalizeInvoice_JsonObjectMendixObject = finalizeInvoice_JsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FinalizeInvoice_JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.Integer amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of Amount_excluding_tax
	 */
	public final java.lang.Integer getAmount_excluding_tax()
	{
		return getAmount_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_excluding_tax
	 */
	public final java.lang.Integer getAmount_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_excluding_tax.toString());
	}

	/**
	 * Set value of Amount_excluding_tax
	 * @param amount_excluding_tax
	 */
	public final void setAmount_excluding_tax(java.lang.Integer amount_excluding_tax)
	{
		setAmount_excluding_tax(getContext(), amount_excluding_tax);
	}

	/**
	 * Set value of Amount_excluding_tax
	 * @param context
	 * @param amount_excluding_tax
	 */
	public final void setAmount_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Amount_excluding_tax.toString(), amount_excluding_tax);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Discountable
	 */
	public final java.lang.Boolean getDiscountable()
	{
		return getDiscountable(getContext());
	}

	/**
	 * @param context
	 * @return value of Discountable
	 */
	public final java.lang.Boolean getDiscountable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Discountable.toString());
	}

	/**
	 * Set value of Discountable
	 * @param discountable
	 */
	public final void setDiscountable(java.lang.Boolean discountable)
	{
		setDiscountable(getContext(), discountable);
	}

	/**
	 * Set value of Discountable
	 * @param context
	 * @param discountable
	 */
	public final void setDiscountable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean discountable)
	{
		getMendixObject().setValue(context, MemberNames.Discountable.toString(), discountable);
	}

	/**
	 * @return value of Invoice_item
	 */
	public final java.lang.String getInvoice_item()
	{
		return getInvoice_item(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_item
	 */
	public final java.lang.String getInvoice_item(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Invoice_item.toString());
	}

	/**
	 * Set value of Invoice_item
	 * @param invoice_item
	 */
	public final void setInvoice_item(java.lang.String invoice_item)
	{
		setInvoice_item(getContext(), invoice_item);
	}

	/**
	 * Set value of Invoice_item
	 * @param context
	 * @param invoice_item
	 */
	public final void setInvoice_item(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String invoice_item)
	{
		getMendixObject().setValue(context, MemberNames.Invoice_item.toString(), invoice_item);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Proration
	 */
	public final java.lang.Boolean getProration()
	{
		return getProration(getContext());
	}

	/**
	 * @param context
	 * @return value of Proration
	 */
	public final java.lang.Boolean getProration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Proration.toString());
	}

	/**
	 * Set value of Proration
	 * @param proration
	 */
	public final void setProration(java.lang.Boolean proration)
	{
		setProration(getContext(), proration);
	}

	/**
	 * Set value of Proration
	 * @param context
	 * @param proration
	 */
	public final void setProration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean proration)
	{
		getMendixObject().setValue(context, MemberNames.Proration.toString(), proration);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Unit_amount_excluding_tax
	 */
	public final java.lang.String getUnit_amount_excluding_tax()
	{
		return getUnit_amount_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_amount_excluding_tax
	 */
	public final java.lang.String getUnit_amount_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit_amount_excluding_tax.toString());
	}

	/**
	 * Set value of Unit_amount_excluding_tax
	 * @param unit_amount_excluding_tax
	 */
	public final void setUnit_amount_excluding_tax(java.lang.String unit_amount_excluding_tax)
	{
		setUnit_amount_excluding_tax(getContext(), unit_amount_excluding_tax);
	}

	/**
	 * Set value of Unit_amount_excluding_tax
	 * @param context
	 * @param unit_amount_excluding_tax
	 */
	public final void setUnit_amount_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit_amount_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Unit_amount_excluding_tax.toString(), unit_amount_excluding_tax);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_JsonObject_FinalizeInvoice_Data
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Data getFinalizeInvoice_JsonObject_FinalizeInvoice_Data() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_JsonObject_FinalizeInvoice_Data(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_JsonObject_FinalizeInvoice_Data
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Data getFinalizeInvoice_JsonObject_FinalizeInvoice_Data(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_JsonObject_FinalizeInvoice_Data.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Data.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_JsonObject_FinalizeInvoice_Data
	 * @param finalizeinvoice_jsonobject_finalizeinvoice_data
	 */
	public final void setFinalizeInvoice_JsonObject_FinalizeInvoice_Data(paymentgatewaystripe.proxies.FinalizeInvoice_Data finalizeinvoice_jsonobject_finalizeinvoice_data)
	{
		setFinalizeInvoice_JsonObject_FinalizeInvoice_Data(getContext(), finalizeinvoice_jsonobject_finalizeinvoice_data);
	}

	/**
	 * Set value of FinalizeInvoice_JsonObject_FinalizeInvoice_Data
	 * @param context
	 * @param finalizeinvoice_jsonobject_finalizeinvoice_data
	 */
	public final void setFinalizeInvoice_JsonObject_FinalizeInvoice_Data(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Data finalizeinvoice_jsonobject_finalizeinvoice_data)
	{
		if (finalizeinvoice_jsonobject_finalizeinvoice_data == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_JsonObject_FinalizeInvoice_Data.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_JsonObject_FinalizeInvoice_Data.toString(), finalizeinvoice_jsonobject_finalizeinvoice_data.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts getFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts getFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Discount_amounts finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Discount_amounts_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_discount_amounts_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoices_Discounts getFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoices_Discounts getFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoices_Discounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoices_Discounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject
	 * @param finalizeinvoices_discounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoices_Discounts finalizeinvoices_discounts_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject(getContext(), finalizeinvoices_discounts_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoices_discounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoices_Discounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoices_Discounts finalizeinvoices_discounts_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoices_discounts_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoices_Discounts_FinalizeInvoice_JsonObject.toString(), finalizeinvoices_discounts_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Metadata getFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Metadata getFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Metadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Metadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_metadata_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Metadata finalizeinvoice_metadata_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_metadata_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_metadata_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Metadata_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Metadata finalizeinvoice_metadata_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_metadata_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Metadata_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_metadata_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Period_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Period getFinalizeInvoice_Period_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Period_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Period_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Period getFinalizeInvoice_Period_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Period result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Period_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Period.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Period_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_period_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Period_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Period finalizeinvoice_period_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Period_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_period_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Period_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_period_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Period_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Period finalizeinvoice_period_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_period_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Period_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Period_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_period_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Price_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Price getFinalizeInvoice_Price_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Price_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Price_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Price getFinalizeInvoice_Price_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Price result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Price_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Price.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Price_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_price_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Price_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Price finalizeinvoice_price_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Price_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_price_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Price_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_price_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Price_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Price finalizeinvoice_price_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_price_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Price_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Price_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_price_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details getFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details getFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_proration_details_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details finalizeinvoice_proration_details_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_proration_details_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_proration_details_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Proration_details finalizeinvoice_proration_details_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_proration_details_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Proration_details_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_proration_details_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts getFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts getFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Tax_amounts finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Tax_amounts_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_tax_amounts_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates getFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject() throws com.mendix.core.CoreException
	{
		return getFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates getFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject
	 * @param finalizeinvoice_tax_rates_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject(paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates finalizeinvoice_tax_rates_finalizeinvoice_jsonobject)
	{
		setFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject(getContext(), finalizeinvoice_tax_rates_finalizeinvoice_jsonobject);
	}

	/**
	 * Set value of FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject
	 * @param context
	 * @param finalizeinvoice_tax_rates_finalizeinvoice_jsonobject
	 */
	public final void setFinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.FinalizeInvoice_Tax_rates finalizeinvoice_tax_rates_finalizeinvoice_jsonobject)
	{
		if (finalizeinvoice_tax_rates_finalizeinvoice_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FinalizeInvoice_Tax_rates_FinalizeInvoice_JsonObject.toString(), finalizeinvoice_tax_rates_finalizeinvoice_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return finalizeInvoice_JsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject that = (paymentgatewaystripe.proxies.FinalizeInvoice_JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
