// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class Invoice_Data
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject invoice_DataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.Invoice_Data";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Invoice_Data_Invoice_Lines("PaymentGatewayStripe.Invoice_Data_Invoice_Lines");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Invoice_Data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Invoice_Data(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invoice_DataMendixObject)
	{
		if (invoice_DataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, invoice_DataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.invoice_DataMendixObject = invoice_DataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Invoice_Data.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.Invoice_Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.Invoice_Data.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.Invoice_Data initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.Invoice_Data(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.Invoice_Data load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.Invoice_Data.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Data_Invoice_Lines
	 */
	public final paymentgatewaystripe.proxies.Invoice_Lines getInvoice_Data_Invoice_Lines() throws com.mendix.core.CoreException
	{
		return getInvoice_Data_Invoice_Lines(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Data_Invoice_Lines
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Lines getInvoice_Data_Invoice_Lines(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Lines result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Data_Invoice_Lines.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Lines.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Data_Invoice_Lines
	 * @param invoice_data_invoice_lines
	 */
	public final void setInvoice_Data_Invoice_Lines(paymentgatewaystripe.proxies.Invoice_Lines invoice_data_invoice_lines)
	{
		setInvoice_Data_Invoice_Lines(getContext(), invoice_data_invoice_lines);
	}

	/**
	 * Set value of Invoice_Data_Invoice_Lines
	 * @param context
	 * @param invoice_data_invoice_lines
	 */
	public final void setInvoice_Data_Invoice_Lines(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Lines invoice_data_invoice_lines)
	{
		if (invoice_data_invoice_lines == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Data_Invoice_Lines.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Data_Invoice_Lines.toString(), invoice_data_invoice_lines.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return invoice_DataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.Invoice_Data that = (paymentgatewaystripe.proxies.Invoice_Data) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
