// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class InvoiceLineItem_Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject invoiceLineItem_RootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.InvoiceLineItem_Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Amount("Amount"),
		Currency("Currency"),
		Customer("Customer"),
		Date("Date"),
		Description("Description"),
		Discountable("Discountable"),
		Invoice("Invoice"),
		Livemode("Livemode"),
		Proration("Proration"),
		Quantity("Quantity"),
		Unit_amount("Unit_amount"),
		Unit_amount_decimal("Unit_amount_decimal"),
		InvoiceLineItem_Discounts_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Discounts_InvoiceLineItem_Root"),
		InvoiceLineItem_Metadata_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Metadata_InvoiceLineItem_Root"),
		InvoiceLineItem_Period_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Period_InvoiceLineItem_Root"),
		InvoiceLineItem_Price_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Price_InvoiceLineItem_Root"),
		InvoiceLineItem_Tax_rates_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Tax_rates_InvoiceLineItem_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invoiceLineItem_RootMendixObject)
	{
		if (invoiceLineItem_RootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, invoiceLineItem_RootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.invoiceLineItem_RootMendixObject = invoiceLineItem_RootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InvoiceLineItem_Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.InvoiceLineItem_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.InvoiceLineItem_Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.InvoiceLineItem_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.InvoiceLineItem_Root(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.InvoiceLineItem_Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.InvoiceLineItem_Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.lang.Integer getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.lang.Integer amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer()
	{
		return getCustomer(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer.toString());
	}

	/**
	 * Set value of Customer
	 * @param customer
	 */
	public final void setCustomer(java.lang.String customer)
	{
		setCustomer(getContext(), customer);
	}

	/**
	 * Set value of Customer
	 * @param context
	 * @param customer
	 */
	public final void setCustomer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer)
	{
		getMendixObject().setValue(context, MemberNames.Customer.toString(), customer);
	}

	/**
	 * @return value of Date
	 */
	public final java.lang.Integer getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.lang.Integer getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.lang.Integer date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Discountable
	 */
	public final java.lang.Boolean getDiscountable()
	{
		return getDiscountable(getContext());
	}

	/**
	 * @param context
	 * @return value of Discountable
	 */
	public final java.lang.Boolean getDiscountable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Discountable.toString());
	}

	/**
	 * Set value of Discountable
	 * @param discountable
	 */
	public final void setDiscountable(java.lang.Boolean discountable)
	{
		setDiscountable(getContext(), discountable);
	}

	/**
	 * Set value of Discountable
	 * @param context
	 * @param discountable
	 */
	public final void setDiscountable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean discountable)
	{
		getMendixObject().setValue(context, MemberNames.Discountable.toString(), discountable);
	}

	/**
	 * @return value of Invoice
	 */
	public final java.lang.String getInvoice()
	{
		return getInvoice(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice
	 */
	public final java.lang.String getInvoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Invoice.toString());
	}

	/**
	 * Set value of Invoice
	 * @param invoice
	 */
	public final void setInvoice(java.lang.String invoice)
	{
		setInvoice(getContext(), invoice);
	}

	/**
	 * Set value of Invoice
	 * @param context
	 * @param invoice
	 */
	public final void setInvoice(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String invoice)
	{
		getMendixObject().setValue(context, MemberNames.Invoice.toString(), invoice);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Proration
	 */
	public final java.lang.Boolean getProration()
	{
		return getProration(getContext());
	}

	/**
	 * @param context
	 * @return value of Proration
	 */
	public final java.lang.Boolean getProration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Proration.toString());
	}

	/**
	 * Set value of Proration
	 * @param proration
	 */
	public final void setProration(java.lang.Boolean proration)
	{
		setProration(getContext(), proration);
	}

	/**
	 * Set value of Proration
	 * @param context
	 * @param proration
	 */
	public final void setProration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean proration)
	{
		getMendixObject().setValue(context, MemberNames.Proration.toString(), proration);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of Unit_amount
	 */
	public final java.lang.Integer getUnit_amount()
	{
		return getUnit_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_amount
	 */
	public final java.lang.Integer getUnit_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Unit_amount.toString());
	}

	/**
	 * Set value of Unit_amount
	 * @param unit_amount
	 */
	public final void setUnit_amount(java.lang.Integer unit_amount)
	{
		setUnit_amount(getContext(), unit_amount);
	}

	/**
	 * Set value of Unit_amount
	 * @param context
	 * @param unit_amount
	 */
	public final void setUnit_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer unit_amount)
	{
		getMendixObject().setValue(context, MemberNames.Unit_amount.toString(), unit_amount);
	}

	/**
	 * @return value of Unit_amount_decimal
	 */
	public final java.lang.String getUnit_amount_decimal()
	{
		return getUnit_amount_decimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_amount_decimal
	 */
	public final java.lang.String getUnit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit_amount_decimal.toString());
	}

	/**
	 * Set value of Unit_amount_decimal
	 * @param unit_amount_decimal
	 */
	public final void setUnit_amount_decimal(java.lang.String unit_amount_decimal)
	{
		setUnit_amount_decimal(getContext(), unit_amount_decimal);
	}

	/**
	 * Set value of Unit_amount_decimal
	 * @param context
	 * @param unit_amount_decimal
	 */
	public final void setUnit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit_amount_decimal)
	{
		getMendixObject().setValue(context, MemberNames.Unit_amount_decimal.toString(), unit_amount_decimal);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Discounts_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Discounts getInvoiceLineItem_Discounts_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Discounts_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Discounts_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Discounts getInvoiceLineItem_Discounts_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Discounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Discounts_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Discounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Discounts_InvoiceLineItem_Root
	 * @param invoicelineitem_discounts_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Discounts_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Discounts invoicelineitem_discounts_invoicelineitem_root)
	{
		setInvoiceLineItem_Discounts_InvoiceLineItem_Root(getContext(), invoicelineitem_discounts_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Discounts_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_discounts_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Discounts_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Discounts invoicelineitem_discounts_invoicelineitem_root)
	{
		if (invoicelineitem_discounts_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Discounts_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Discounts_InvoiceLineItem_Root.toString(), invoicelineitem_discounts_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Metadata_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Metadata getInvoiceLineItem_Metadata_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Metadata_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Metadata_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Metadata getInvoiceLineItem_Metadata_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Metadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Metadata_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Metadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Metadata_InvoiceLineItem_Root
	 * @param invoicelineitem_metadata_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Metadata_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Metadata invoicelineitem_metadata_invoicelineitem_root)
	{
		setInvoiceLineItem_Metadata_InvoiceLineItem_Root(getContext(), invoicelineitem_metadata_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Metadata_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_metadata_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Metadata_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Metadata invoicelineitem_metadata_invoicelineitem_root)
	{
		if (invoicelineitem_metadata_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Metadata_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Metadata_InvoiceLineItem_Root.toString(), invoicelineitem_metadata_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Period_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Period getInvoiceLineItem_Period_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Period_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Period_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Period getInvoiceLineItem_Period_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Period result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Period_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Period.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Period_InvoiceLineItem_Root
	 * @param invoicelineitem_period_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Period_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Period invoicelineitem_period_invoicelineitem_root)
	{
		setInvoiceLineItem_Period_InvoiceLineItem_Root(getContext(), invoicelineitem_period_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Period_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_period_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Period_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Period invoicelineitem_period_invoicelineitem_root)
	{
		if (invoicelineitem_period_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Period_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Period_InvoiceLineItem_Root.toString(), invoicelineitem_period_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Price getInvoiceLineItem_Price_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Price_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Price getInvoiceLineItem_Price_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Price result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Price.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @param invoicelineitem_price_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Price_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Price invoicelineitem_price_invoicelineitem_root)
	{
		setInvoiceLineItem_Price_InvoiceLineItem_Root(getContext(), invoicelineitem_price_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_price_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Price_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Price invoicelineitem_price_invoicelineitem_root)
	{
		if (invoicelineitem_price_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString(), invoicelineitem_price_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Tax_rates_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates getInvoiceLineItem_Tax_rates_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Tax_rates_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Tax_rates_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates getInvoiceLineItem_Tax_rates_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Tax_rates_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Tax_rates_InvoiceLineItem_Root
	 * @param invoicelineitem_tax_rates_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Tax_rates_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates invoicelineitem_tax_rates_invoicelineitem_root)
	{
		setInvoiceLineItem_Tax_rates_InvoiceLineItem_Root(getContext(), invoicelineitem_tax_rates_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Tax_rates_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_tax_rates_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Tax_rates_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Tax_rates invoicelineitem_tax_rates_invoicelineitem_root)
	{
		if (invoicelineitem_tax_rates_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Tax_rates_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Tax_rates_InvoiceLineItem_Root.toString(), invoicelineitem_tax_rates_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return invoiceLineItem_RootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.InvoiceLineItem_Root that = (paymentgatewaystripe.proxies.InvoiceLineItem_Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
