// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class Invoice_Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject invoice_RootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.Invoice_Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Account_country("Account_country"),
		Account_name("Account_name"),
		Amount_due("Amount_due"),
		Amount_paid("Amount_paid"),
		Amount_remaining("Amount_remaining"),
		Attempt_count("Attempt_count"),
		Attempted("Attempted"),
		Auto_advance("Auto_advance"),
		Billing_reason("Billing_reason"),
		Collection_method("Collection_method"),
		Created("Created"),
		Currency("Currency"),
		Customer("Customer"),
		Customer_email("Customer_email"),
		Customer_name("Customer_name"),
		Customer_tax_exempt("Customer_tax_exempt"),
		Livemode("Livemode"),
		Paid("Paid"),
		Paid_out_of_band("Paid_out_of_band"),
		Period_end("Period_end"),
		Period_start("Period_start"),
		Post_payment_credit_notes_amount("Post_payment_credit_notes_amount"),
		Pre_payment_credit_notes_amount("Pre_payment_credit_notes_amount"),
		Starting_balance("Starting_balance"),
		Status("Status"),
		Subtotal("Subtotal"),
		Subtotal_excluding_tax("Subtotal_excluding_tax"),
		Total("Total"),
		Total_excluding_tax("Total_excluding_tax"),
		Invoice_Automatic_tax_Invoice_Root("PaymentGatewayStripe.Invoice_Automatic_tax_Invoice_Root"),
		Invoice_Customer_address_Invoice_Root("PaymentGatewayStripe.Invoice_Customer_address_Invoice_Root"),
		Invoice_Customer_tax_ids_Invoice_Root("PaymentGatewayStripe.Invoice_Customer_tax_ids_Invoice_Root"),
		Invoice_Default_tax_rates_Invoice_Root("PaymentGatewayStripe.Invoice_Default_tax_rates_Invoice_Root"),
		Invoice_Discounts_Invoice_Root("PaymentGatewayStripe.Invoice_Discounts_Invoice_Root"),
		Invoice_Lines_Invoice_Root("PaymentGatewayStripe.Invoice_Lines_Invoice_Root"),
		Invoice_Metadata_Invoice_Root("PaymentGatewayStripe.Invoice_Metadata_Invoice_Root"),
		Invoice_Payment_settings_Invoice_Root("PaymentGatewayStripe.Invoice_Payment_settings_Invoice_Root"),
		Invoice_Status_transitions_Invoice_Root("PaymentGatewayStripe.Invoice_Status_transitions_Invoice_Root"),
		Invoice_Total_discount_amounts_Invoice_Root("PaymentGatewayStripe.Invoice_Total_discount_amounts_Invoice_Root"),
		Invoice_Total_tax_amounts_Invoice_Root("PaymentGatewayStripe.Invoice_Total_tax_amounts_Invoice_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invoice_RootMendixObject)
	{
		if (invoice_RootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, invoice_RootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.invoice_RootMendixObject = invoice_RootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Invoice_Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.Invoice_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.Invoice_Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.Invoice_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.Invoice_Root(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.Invoice_Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.Invoice_Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Account_country
	 */
	public final java.lang.String getAccount_country()
	{
		return getAccount_country(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_country
	 */
	public final java.lang.String getAccount_country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account_country.toString());
	}

	/**
	 * Set value of Account_country
	 * @param account_country
	 */
	public final void setAccount_country(java.lang.String account_country)
	{
		setAccount_country(getContext(), account_country);
	}

	/**
	 * Set value of Account_country
	 * @param context
	 * @param account_country
	 */
	public final void setAccount_country(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account_country)
	{
		getMendixObject().setValue(context, MemberNames.Account_country.toString(), account_country);
	}

	/**
	 * @return value of Account_name
	 */
	public final java.lang.String getAccount_name()
	{
		return getAccount_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_name
	 */
	public final java.lang.String getAccount_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account_name.toString());
	}

	/**
	 * Set value of Account_name
	 * @param account_name
	 */
	public final void setAccount_name(java.lang.String account_name)
	{
		setAccount_name(getContext(), account_name);
	}

	/**
	 * Set value of Account_name
	 * @param context
	 * @param account_name
	 */
	public final void setAccount_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account_name)
	{
		getMendixObject().setValue(context, MemberNames.Account_name.toString(), account_name);
	}

	/**
	 * @return value of Amount_due
	 */
	public final java.lang.Integer getAmount_due()
	{
		return getAmount_due(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_due
	 */
	public final java.lang.Integer getAmount_due(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_due.toString());
	}

	/**
	 * Set value of Amount_due
	 * @param amount_due
	 */
	public final void setAmount_due(java.lang.Integer amount_due)
	{
		setAmount_due(getContext(), amount_due);
	}

	/**
	 * Set value of Amount_due
	 * @param context
	 * @param amount_due
	 */
	public final void setAmount_due(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_due)
	{
		getMendixObject().setValue(context, MemberNames.Amount_due.toString(), amount_due);
	}

	/**
	 * @return value of Amount_paid
	 */
	public final java.lang.Integer getAmount_paid()
	{
		return getAmount_paid(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_paid
	 */
	public final java.lang.Integer getAmount_paid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_paid.toString());
	}

	/**
	 * Set value of Amount_paid
	 * @param amount_paid
	 */
	public final void setAmount_paid(java.lang.Integer amount_paid)
	{
		setAmount_paid(getContext(), amount_paid);
	}

	/**
	 * Set value of Amount_paid
	 * @param context
	 * @param amount_paid
	 */
	public final void setAmount_paid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_paid)
	{
		getMendixObject().setValue(context, MemberNames.Amount_paid.toString(), amount_paid);
	}

	/**
	 * @return value of Amount_remaining
	 */
	public final java.lang.Integer getAmount_remaining()
	{
		return getAmount_remaining(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount_remaining
	 */
	public final java.lang.Integer getAmount_remaining(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Amount_remaining.toString());
	}

	/**
	 * Set value of Amount_remaining
	 * @param amount_remaining
	 */
	public final void setAmount_remaining(java.lang.Integer amount_remaining)
	{
		setAmount_remaining(getContext(), amount_remaining);
	}

	/**
	 * Set value of Amount_remaining
	 * @param context
	 * @param amount_remaining
	 */
	public final void setAmount_remaining(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer amount_remaining)
	{
		getMendixObject().setValue(context, MemberNames.Amount_remaining.toString(), amount_remaining);
	}

	/**
	 * @return value of Attempt_count
	 */
	public final java.lang.Integer getAttempt_count()
	{
		return getAttempt_count(getContext());
	}

	/**
	 * @param context
	 * @return value of Attempt_count
	 */
	public final java.lang.Integer getAttempt_count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Attempt_count.toString());
	}

	/**
	 * Set value of Attempt_count
	 * @param attempt_count
	 */
	public final void setAttempt_count(java.lang.Integer attempt_count)
	{
		setAttempt_count(getContext(), attempt_count);
	}

	/**
	 * Set value of Attempt_count
	 * @param context
	 * @param attempt_count
	 */
	public final void setAttempt_count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attempt_count)
	{
		getMendixObject().setValue(context, MemberNames.Attempt_count.toString(), attempt_count);
	}

	/**
	 * @return value of Attempted
	 */
	public final java.lang.Boolean getAttempted()
	{
		return getAttempted(getContext());
	}

	/**
	 * @param context
	 * @return value of Attempted
	 */
	public final java.lang.Boolean getAttempted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Attempted.toString());
	}

	/**
	 * Set value of Attempted
	 * @param attempted
	 */
	public final void setAttempted(java.lang.Boolean attempted)
	{
		setAttempted(getContext(), attempted);
	}

	/**
	 * Set value of Attempted
	 * @param context
	 * @param attempted
	 */
	public final void setAttempted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attempted)
	{
		getMendixObject().setValue(context, MemberNames.Attempted.toString(), attempted);
	}

	/**
	 * @return value of Auto_advance
	 */
	public final java.lang.Boolean getAuto_advance()
	{
		return getAuto_advance(getContext());
	}

	/**
	 * @param context
	 * @return value of Auto_advance
	 */
	public final java.lang.Boolean getAuto_advance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Auto_advance.toString());
	}

	/**
	 * Set value of Auto_advance
	 * @param auto_advance
	 */
	public final void setAuto_advance(java.lang.Boolean auto_advance)
	{
		setAuto_advance(getContext(), auto_advance);
	}

	/**
	 * Set value of Auto_advance
	 * @param context
	 * @param auto_advance
	 */
	public final void setAuto_advance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean auto_advance)
	{
		getMendixObject().setValue(context, MemberNames.Auto_advance.toString(), auto_advance);
	}

	/**
	 * @return value of Billing_reason
	 */
	public final java.lang.String getBilling_reason()
	{
		return getBilling_reason(getContext());
	}

	/**
	 * @param context
	 * @return value of Billing_reason
	 */
	public final java.lang.String getBilling_reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Billing_reason.toString());
	}

	/**
	 * Set value of Billing_reason
	 * @param billing_reason
	 */
	public final void setBilling_reason(java.lang.String billing_reason)
	{
		setBilling_reason(getContext(), billing_reason);
	}

	/**
	 * Set value of Billing_reason
	 * @param context
	 * @param billing_reason
	 */
	public final void setBilling_reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billing_reason)
	{
		getMendixObject().setValue(context, MemberNames.Billing_reason.toString(), billing_reason);
	}

	/**
	 * @return value of Collection_method
	 */
	public final java.lang.String getCollection_method()
	{
		return getCollection_method(getContext());
	}

	/**
	 * @param context
	 * @return value of Collection_method
	 */
	public final java.lang.String getCollection_method(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Collection_method.toString());
	}

	/**
	 * Set value of Collection_method
	 * @param collection_method
	 */
	public final void setCollection_method(java.lang.String collection_method)
	{
		setCollection_method(getContext(), collection_method);
	}

	/**
	 * Set value of Collection_method
	 * @param context
	 * @param collection_method
	 */
	public final void setCollection_method(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String collection_method)
	{
		getMendixObject().setValue(context, MemberNames.Collection_method.toString(), collection_method);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer()
	{
		return getCustomer(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer
	 */
	public final java.lang.String getCustomer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer.toString());
	}

	/**
	 * Set value of Customer
	 * @param customer
	 */
	public final void setCustomer(java.lang.String customer)
	{
		setCustomer(getContext(), customer);
	}

	/**
	 * Set value of Customer
	 * @param context
	 * @param customer
	 */
	public final void setCustomer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer)
	{
		getMendixObject().setValue(context, MemberNames.Customer.toString(), customer);
	}

	/**
	 * @return value of Customer_email
	 */
	public final java.lang.String getCustomer_email()
	{
		return getCustomer_email(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_email
	 */
	public final java.lang.String getCustomer_email(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_email.toString());
	}

	/**
	 * Set value of Customer_email
	 * @param customer_email
	 */
	public final void setCustomer_email(java.lang.String customer_email)
	{
		setCustomer_email(getContext(), customer_email);
	}

	/**
	 * Set value of Customer_email
	 * @param context
	 * @param customer_email
	 */
	public final void setCustomer_email(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_email)
	{
		getMendixObject().setValue(context, MemberNames.Customer_email.toString(), customer_email);
	}

	/**
	 * @return value of Customer_name
	 */
	public final java.lang.String getCustomer_name()
	{
		return getCustomer_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_name
	 */
	public final java.lang.String getCustomer_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_name.toString());
	}

	/**
	 * Set value of Customer_name
	 * @param customer_name
	 */
	public final void setCustomer_name(java.lang.String customer_name)
	{
		setCustomer_name(getContext(), customer_name);
	}

	/**
	 * Set value of Customer_name
	 * @param context
	 * @param customer_name
	 */
	public final void setCustomer_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_name)
	{
		getMendixObject().setValue(context, MemberNames.Customer_name.toString(), customer_name);
	}

	/**
	 * @return value of Customer_tax_exempt
	 */
	public final java.lang.String getCustomer_tax_exempt()
	{
		return getCustomer_tax_exempt(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_tax_exempt
	 */
	public final java.lang.String getCustomer_tax_exempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_tax_exempt.toString());
	}

	/**
	 * Set value of Customer_tax_exempt
	 * @param customer_tax_exempt
	 */
	public final void setCustomer_tax_exempt(java.lang.String customer_tax_exempt)
	{
		setCustomer_tax_exempt(getContext(), customer_tax_exempt);
	}

	/**
	 * Set value of Customer_tax_exempt
	 * @param context
	 * @param customer_tax_exempt
	 */
	public final void setCustomer_tax_exempt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_tax_exempt)
	{
		getMendixObject().setValue(context, MemberNames.Customer_tax_exempt.toString(), customer_tax_exempt);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Paid
	 */
	public final java.lang.Boolean getPaid()
	{
		return getPaid(getContext());
	}

	/**
	 * @param context
	 * @return value of Paid
	 */
	public final java.lang.Boolean getPaid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Paid.toString());
	}

	/**
	 * Set value of Paid
	 * @param paid
	 */
	public final void setPaid(java.lang.Boolean paid)
	{
		setPaid(getContext(), paid);
	}

	/**
	 * Set value of Paid
	 * @param context
	 * @param paid
	 */
	public final void setPaid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean paid)
	{
		getMendixObject().setValue(context, MemberNames.Paid.toString(), paid);
	}

	/**
	 * @return value of Paid_out_of_band
	 */
	public final java.lang.Boolean getPaid_out_of_band()
	{
		return getPaid_out_of_band(getContext());
	}

	/**
	 * @param context
	 * @return value of Paid_out_of_band
	 */
	public final java.lang.Boolean getPaid_out_of_band(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Paid_out_of_band.toString());
	}

	/**
	 * Set value of Paid_out_of_band
	 * @param paid_out_of_band
	 */
	public final void setPaid_out_of_band(java.lang.Boolean paid_out_of_band)
	{
		setPaid_out_of_band(getContext(), paid_out_of_band);
	}

	/**
	 * Set value of Paid_out_of_band
	 * @param context
	 * @param paid_out_of_band
	 */
	public final void setPaid_out_of_band(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean paid_out_of_band)
	{
		getMendixObject().setValue(context, MemberNames.Paid_out_of_band.toString(), paid_out_of_band);
	}

	/**
	 * @return value of Period_end
	 */
	public final java.lang.Integer getPeriod_end()
	{
		return getPeriod_end(getContext());
	}

	/**
	 * @param context
	 * @return value of Period_end
	 */
	public final java.lang.Integer getPeriod_end(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Period_end.toString());
	}

	/**
	 * Set value of Period_end
	 * @param period_end
	 */
	public final void setPeriod_end(java.lang.Integer period_end)
	{
		setPeriod_end(getContext(), period_end);
	}

	/**
	 * Set value of Period_end
	 * @param context
	 * @param period_end
	 */
	public final void setPeriod_end(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer period_end)
	{
		getMendixObject().setValue(context, MemberNames.Period_end.toString(), period_end);
	}

	/**
	 * @return value of Period_start
	 */
	public final java.lang.Integer getPeriod_start()
	{
		return getPeriod_start(getContext());
	}

	/**
	 * @param context
	 * @return value of Period_start
	 */
	public final java.lang.Integer getPeriod_start(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Period_start.toString());
	}

	/**
	 * Set value of Period_start
	 * @param period_start
	 */
	public final void setPeriod_start(java.lang.Integer period_start)
	{
		setPeriod_start(getContext(), period_start);
	}

	/**
	 * Set value of Period_start
	 * @param context
	 * @param period_start
	 */
	public final void setPeriod_start(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer period_start)
	{
		getMendixObject().setValue(context, MemberNames.Period_start.toString(), period_start);
	}

	/**
	 * @return value of Post_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPost_payment_credit_notes_amount()
	{
		return getPost_payment_credit_notes_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Post_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPost_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Post_payment_credit_notes_amount.toString());
	}

	/**
	 * Set value of Post_payment_credit_notes_amount
	 * @param post_payment_credit_notes_amount
	 */
	public final void setPost_payment_credit_notes_amount(java.lang.Integer post_payment_credit_notes_amount)
	{
		setPost_payment_credit_notes_amount(getContext(), post_payment_credit_notes_amount);
	}

	/**
	 * Set value of Post_payment_credit_notes_amount
	 * @param context
	 * @param post_payment_credit_notes_amount
	 */
	public final void setPost_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer post_payment_credit_notes_amount)
	{
		getMendixObject().setValue(context, MemberNames.Post_payment_credit_notes_amount.toString(), post_payment_credit_notes_amount);
	}

	/**
	 * @return value of Pre_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPre_payment_credit_notes_amount()
	{
		return getPre_payment_credit_notes_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Pre_payment_credit_notes_amount
	 */
	public final java.lang.Integer getPre_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pre_payment_credit_notes_amount.toString());
	}

	/**
	 * Set value of Pre_payment_credit_notes_amount
	 * @param pre_payment_credit_notes_amount
	 */
	public final void setPre_payment_credit_notes_amount(java.lang.Integer pre_payment_credit_notes_amount)
	{
		setPre_payment_credit_notes_amount(getContext(), pre_payment_credit_notes_amount);
	}

	/**
	 * Set value of Pre_payment_credit_notes_amount
	 * @param context
	 * @param pre_payment_credit_notes_amount
	 */
	public final void setPre_payment_credit_notes_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pre_payment_credit_notes_amount)
	{
		getMendixObject().setValue(context, MemberNames.Pre_payment_credit_notes_amount.toString(), pre_payment_credit_notes_amount);
	}

	/**
	 * @return value of Starting_balance
	 */
	public final java.lang.Integer getStarting_balance()
	{
		return getStarting_balance(getContext());
	}

	/**
	 * @param context
	 * @return value of Starting_balance
	 */
	public final java.lang.Integer getStarting_balance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Starting_balance.toString());
	}

	/**
	 * Set value of Starting_balance
	 * @param starting_balance
	 */
	public final void setStarting_balance(java.lang.Integer starting_balance)
	{
		setStarting_balance(getContext(), starting_balance);
	}

	/**
	 * Set value of Starting_balance
	 * @param context
	 * @param starting_balance
	 */
	public final void setStarting_balance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer starting_balance)
	{
		getMendixObject().setValue(context, MemberNames.Starting_balance.toString(), starting_balance);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Subtotal
	 */
	public final java.lang.Integer getSubtotal()
	{
		return getSubtotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Subtotal
	 */
	public final java.lang.Integer getSubtotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Subtotal.toString());
	}

	/**
	 * Set value of Subtotal
	 * @param subtotal
	 */
	public final void setSubtotal(java.lang.Integer subtotal)
	{
		setSubtotal(getContext(), subtotal);
	}

	/**
	 * Set value of Subtotal
	 * @param context
	 * @param subtotal
	 */
	public final void setSubtotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer subtotal)
	{
		getMendixObject().setValue(context, MemberNames.Subtotal.toString(), subtotal);
	}

	/**
	 * @return value of Subtotal_excluding_tax
	 */
	public final java.lang.Integer getSubtotal_excluding_tax()
	{
		return getSubtotal_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Subtotal_excluding_tax
	 */
	public final java.lang.Integer getSubtotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Subtotal_excluding_tax.toString());
	}

	/**
	 * Set value of Subtotal_excluding_tax
	 * @param subtotal_excluding_tax
	 */
	public final void setSubtotal_excluding_tax(java.lang.Integer subtotal_excluding_tax)
	{
		setSubtotal_excluding_tax(getContext(), subtotal_excluding_tax);
	}

	/**
	 * Set value of Subtotal_excluding_tax
	 * @param context
	 * @param subtotal_excluding_tax
	 */
	public final void setSubtotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer subtotal_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Subtotal_excluding_tax.toString(), subtotal_excluding_tax);
	}

	/**
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal()
	{
		return getTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total.toString());
	}

	/**
	 * Set value of Total
	 * @param total
	 */
	public final void setTotal(java.lang.Integer total)
	{
		setTotal(getContext(), total);
	}

	/**
	 * Set value of Total
	 * @param context
	 * @param total
	 */
	public final void setTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total)
	{
		getMendixObject().setValue(context, MemberNames.Total.toString(), total);
	}

	/**
	 * @return value of Total_excluding_tax
	 */
	public final java.lang.Integer getTotal_excluding_tax()
	{
		return getTotal_excluding_tax(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_excluding_tax
	 */
	public final java.lang.Integer getTotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total_excluding_tax.toString());
	}

	/**
	 * Set value of Total_excluding_tax
	 * @param total_excluding_tax
	 */
	public final void setTotal_excluding_tax(java.lang.Integer total_excluding_tax)
	{
		setTotal_excluding_tax(getContext(), total_excluding_tax);
	}

	/**
	 * Set value of Total_excluding_tax
	 * @param context
	 * @param total_excluding_tax
	 */
	public final void setTotal_excluding_tax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total_excluding_tax)
	{
		getMendixObject().setValue(context, MemberNames.Total_excluding_tax.toString(), total_excluding_tax);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Automatic_tax_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Automatic_tax getInvoice_Automatic_tax_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Automatic_tax_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Automatic_tax_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Automatic_tax getInvoice_Automatic_tax_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Automatic_tax result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Automatic_tax_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Automatic_tax.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Automatic_tax_Invoice_Root
	 * @param invoice_automatic_tax_invoice_root
	 */
	public final void setInvoice_Automatic_tax_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Automatic_tax invoice_automatic_tax_invoice_root)
	{
		setInvoice_Automatic_tax_Invoice_Root(getContext(), invoice_automatic_tax_invoice_root);
	}

	/**
	 * Set value of Invoice_Automatic_tax_Invoice_Root
	 * @param context
	 * @param invoice_automatic_tax_invoice_root
	 */
	public final void setInvoice_Automatic_tax_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Automatic_tax invoice_automatic_tax_invoice_root)
	{
		if (invoice_automatic_tax_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Automatic_tax_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Automatic_tax_Invoice_Root.toString(), invoice_automatic_tax_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Customer_address_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Customer_address getInvoice_Customer_address_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Customer_address_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Customer_address_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Customer_address getInvoice_Customer_address_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Customer_address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Customer_address_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Customer_address.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Customer_address_Invoice_Root
	 * @param invoice_customer_address_invoice_root
	 */
	public final void setInvoice_Customer_address_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Customer_address invoice_customer_address_invoice_root)
	{
		setInvoice_Customer_address_Invoice_Root(getContext(), invoice_customer_address_invoice_root);
	}

	/**
	 * Set value of Invoice_Customer_address_Invoice_Root
	 * @param context
	 * @param invoice_customer_address_invoice_root
	 */
	public final void setInvoice_Customer_address_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Customer_address invoice_customer_address_invoice_root)
	{
		if (invoice_customer_address_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Customer_address_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Customer_address_Invoice_Root.toString(), invoice_customer_address_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Customer_tax_ids_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Customer_tax_ids getInvoice_Customer_tax_ids_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Customer_tax_ids_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Customer_tax_ids_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Customer_tax_ids getInvoice_Customer_tax_ids_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Customer_tax_ids result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Customer_tax_ids_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Customer_tax_ids.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Customer_tax_ids_Invoice_Root
	 * @param invoice_customer_tax_ids_invoice_root
	 */
	public final void setInvoice_Customer_tax_ids_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Customer_tax_ids invoice_customer_tax_ids_invoice_root)
	{
		setInvoice_Customer_tax_ids_Invoice_Root(getContext(), invoice_customer_tax_ids_invoice_root);
	}

	/**
	 * Set value of Invoice_Customer_tax_ids_Invoice_Root
	 * @param context
	 * @param invoice_customer_tax_ids_invoice_root
	 */
	public final void setInvoice_Customer_tax_ids_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Customer_tax_ids invoice_customer_tax_ids_invoice_root)
	{
		if (invoice_customer_tax_ids_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Customer_tax_ids_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Customer_tax_ids_Invoice_Root.toString(), invoice_customer_tax_ids_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Default_tax_rates_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Default_tax_rates getInvoice_Default_tax_rates_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Default_tax_rates_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Default_tax_rates_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Default_tax_rates getInvoice_Default_tax_rates_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Default_tax_rates result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Default_tax_rates_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Default_tax_rates.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Default_tax_rates_Invoice_Root
	 * @param invoice_default_tax_rates_invoice_root
	 */
	public final void setInvoice_Default_tax_rates_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Default_tax_rates invoice_default_tax_rates_invoice_root)
	{
		setInvoice_Default_tax_rates_Invoice_Root(getContext(), invoice_default_tax_rates_invoice_root);
	}

	/**
	 * Set value of Invoice_Default_tax_rates_Invoice_Root
	 * @param context
	 * @param invoice_default_tax_rates_invoice_root
	 */
	public final void setInvoice_Default_tax_rates_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Default_tax_rates invoice_default_tax_rates_invoice_root)
	{
		if (invoice_default_tax_rates_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Default_tax_rates_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Default_tax_rates_Invoice_Root.toString(), invoice_default_tax_rates_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Discounts_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Discounts getInvoice_Discounts_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Discounts_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Discounts_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Discounts getInvoice_Discounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Discounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Discounts_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Discounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Discounts_Invoice_Root
	 * @param invoice_discounts_invoice_root
	 */
	public final void setInvoice_Discounts_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Discounts invoice_discounts_invoice_root)
	{
		setInvoice_Discounts_Invoice_Root(getContext(), invoice_discounts_invoice_root);
	}

	/**
	 * Set value of Invoice_Discounts_Invoice_Root
	 * @param context
	 * @param invoice_discounts_invoice_root
	 */
	public final void setInvoice_Discounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Discounts invoice_discounts_invoice_root)
	{
		if (invoice_discounts_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Discounts_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Discounts_Invoice_Root.toString(), invoice_discounts_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Lines_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Lines getInvoice_Lines_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Lines_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Lines_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Lines getInvoice_Lines_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Lines result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Lines_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Lines.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Lines_Invoice_Root
	 * @param invoice_lines_invoice_root
	 */
	public final void setInvoice_Lines_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Lines invoice_lines_invoice_root)
	{
		setInvoice_Lines_Invoice_Root(getContext(), invoice_lines_invoice_root);
	}

	/**
	 * Set value of Invoice_Lines_Invoice_Root
	 * @param context
	 * @param invoice_lines_invoice_root
	 */
	public final void setInvoice_Lines_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Lines invoice_lines_invoice_root)
	{
		if (invoice_lines_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Lines_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Lines_Invoice_Root.toString(), invoice_lines_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Metadata_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Metadata getInvoice_Metadata_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Metadata_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Metadata_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Metadata getInvoice_Metadata_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Metadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Metadata_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Metadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Metadata_Invoice_Root
	 * @param invoice_metadata_invoice_root
	 */
	public final void setInvoice_Metadata_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Metadata invoice_metadata_invoice_root)
	{
		setInvoice_Metadata_Invoice_Root(getContext(), invoice_metadata_invoice_root);
	}

	/**
	 * Set value of Invoice_Metadata_Invoice_Root
	 * @param context
	 * @param invoice_metadata_invoice_root
	 */
	public final void setInvoice_Metadata_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Metadata invoice_metadata_invoice_root)
	{
		if (invoice_metadata_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Metadata_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Metadata_Invoice_Root.toString(), invoice_metadata_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Payment_settings_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Payment_settings getInvoice_Payment_settings_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Payment_settings_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Payment_settings_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Payment_settings getInvoice_Payment_settings_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Payment_settings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Payment_settings_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Payment_settings.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Payment_settings_Invoice_Root
	 * @param invoice_payment_settings_invoice_root
	 */
	public final void setInvoice_Payment_settings_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Payment_settings invoice_payment_settings_invoice_root)
	{
		setInvoice_Payment_settings_Invoice_Root(getContext(), invoice_payment_settings_invoice_root);
	}

	/**
	 * Set value of Invoice_Payment_settings_Invoice_Root
	 * @param context
	 * @param invoice_payment_settings_invoice_root
	 */
	public final void setInvoice_Payment_settings_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Payment_settings invoice_payment_settings_invoice_root)
	{
		if (invoice_payment_settings_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Payment_settings_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Payment_settings_Invoice_Root.toString(), invoice_payment_settings_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Status_transitions_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Status_transitions getInvoice_Status_transitions_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Status_transitions_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Status_transitions_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Status_transitions getInvoice_Status_transitions_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Status_transitions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Status_transitions_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Status_transitions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Status_transitions_Invoice_Root
	 * @param invoice_status_transitions_invoice_root
	 */
	public final void setInvoice_Status_transitions_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Status_transitions invoice_status_transitions_invoice_root)
	{
		setInvoice_Status_transitions_Invoice_Root(getContext(), invoice_status_transitions_invoice_root);
	}

	/**
	 * Set value of Invoice_Status_transitions_Invoice_Root
	 * @param context
	 * @param invoice_status_transitions_invoice_root
	 */
	public final void setInvoice_Status_transitions_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Status_transitions invoice_status_transitions_invoice_root)
	{
		if (invoice_status_transitions_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Status_transitions_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Status_transitions_Invoice_Root.toString(), invoice_status_transitions_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Total_discount_amounts_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Total_discount_amounts getInvoice_Total_discount_amounts_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Total_discount_amounts_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Total_discount_amounts_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Total_discount_amounts getInvoice_Total_discount_amounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Total_discount_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Total_discount_amounts_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Total_discount_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Total_discount_amounts_Invoice_Root
	 * @param invoice_total_discount_amounts_invoice_root
	 */
	public final void setInvoice_Total_discount_amounts_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Total_discount_amounts invoice_total_discount_amounts_invoice_root)
	{
		setInvoice_Total_discount_amounts_Invoice_Root(getContext(), invoice_total_discount_amounts_invoice_root);
	}

	/**
	 * Set value of Invoice_Total_discount_amounts_Invoice_Root
	 * @param context
	 * @param invoice_total_discount_amounts_invoice_root
	 */
	public final void setInvoice_Total_discount_amounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Total_discount_amounts invoice_total_discount_amounts_invoice_root)
	{
		if (invoice_total_discount_amounts_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Total_discount_amounts_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Total_discount_amounts_Invoice_Root.toString(), invoice_total_discount_amounts_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Invoice_Total_tax_amounts_Invoice_Root
	 */
	public final paymentgatewaystripe.proxies.Invoice_Total_tax_amounts getInvoice_Total_tax_amounts_Invoice_Root() throws com.mendix.core.CoreException
	{
		return getInvoice_Total_tax_amounts_Invoice_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Invoice_Total_tax_amounts_Invoice_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Invoice_Total_tax_amounts getInvoice_Total_tax_amounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Invoice_Total_tax_amounts result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Invoice_Total_tax_amounts_Invoice_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Invoice_Total_tax_amounts.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Invoice_Total_tax_amounts_Invoice_Root
	 * @param invoice_total_tax_amounts_invoice_root
	 */
	public final void setInvoice_Total_tax_amounts_Invoice_Root(paymentgatewaystripe.proxies.Invoice_Total_tax_amounts invoice_total_tax_amounts_invoice_root)
	{
		setInvoice_Total_tax_amounts_Invoice_Root(getContext(), invoice_total_tax_amounts_invoice_root);
	}

	/**
	 * Set value of Invoice_Total_tax_amounts_Invoice_Root
	 * @param context
	 * @param invoice_total_tax_amounts_invoice_root
	 */
	public final void setInvoice_Total_tax_amounts_Invoice_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Invoice_Total_tax_amounts invoice_total_tax_amounts_invoice_root)
	{
		if (invoice_total_tax_amounts_invoice_root == null) {
			getMendixObject().setValue(context, MemberNames.Invoice_Total_tax_amounts_Invoice_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Invoice_Total_tax_amounts_Invoice_Root.toString(), invoice_total_tax_amounts_invoice_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return invoice_RootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.Invoice_Root that = (paymentgatewaystripe.proxies.Invoice_Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
