// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class InvoiceLineItem_Price
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject invoiceLineItem_PriceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.InvoiceLineItem_Price";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Active("Active"),
		Billing_scheme("Billing_scheme"),
		Created("Created"),
		Currency("Currency"),
		Livemode("Livemode"),
		Product("Product"),
		Tax_behavior("Tax_behavior"),
		_type("_type"),
		Unit_amount("Unit_amount"),
		Unit_amount_decimal("Unit_amount_decimal"),
		InvoiceLineItem_Price_InvoiceLineItem_Root("PaymentGatewayStripe.InvoiceLineItem_Price_InvoiceLineItem_Root"),
		InvoiceLineItem_Metadata_2_InvoiceLineItem_Price("PaymentGatewayStripe.InvoiceLineItem_Metadata_2_InvoiceLineItem_Price");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvoiceLineItem_Price(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvoiceLineItem_Price(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invoiceLineItem_PriceMendixObject)
	{
		if (invoiceLineItem_PriceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, invoiceLineItem_PriceMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.invoiceLineItem_PriceMendixObject = invoiceLineItem_PriceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InvoiceLineItem_Price.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.InvoiceLineItem_Price initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.InvoiceLineItem_Price.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.InvoiceLineItem_Price initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.InvoiceLineItem_Price(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.InvoiceLineItem_Price load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.InvoiceLineItem_Price.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of Billing_scheme
	 */
	public final java.lang.String getBilling_scheme()
	{
		return getBilling_scheme(getContext());
	}

	/**
	 * @param context
	 * @return value of Billing_scheme
	 */
	public final java.lang.String getBilling_scheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Billing_scheme.toString());
	}

	/**
	 * Set value of Billing_scheme
	 * @param billing_scheme
	 */
	public final void setBilling_scheme(java.lang.String billing_scheme)
	{
		setBilling_scheme(getContext(), billing_scheme);
	}

	/**
	 * Set value of Billing_scheme
	 * @param context
	 * @param billing_scheme
	 */
	public final void setBilling_scheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billing_scheme)
	{
		getMendixObject().setValue(context, MemberNames.Billing_scheme.toString(), billing_scheme);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Product
	 */
	public final java.lang.String getProduct()
	{
		return getProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Product
	 */
	public final java.lang.String getProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Product.toString());
	}

	/**
	 * Set value of Product
	 * @param product
	 */
	public final void setProduct(java.lang.String product)
	{
		setProduct(getContext(), product);
	}

	/**
	 * Set value of Product
	 * @param context
	 * @param product
	 */
	public final void setProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.Product.toString(), product);
	}

	/**
	 * @return value of Tax_behavior
	 */
	public final java.lang.String getTax_behavior()
	{
		return getTax_behavior(getContext());
	}

	/**
	 * @param context
	 * @return value of Tax_behavior
	 */
	public final java.lang.String getTax_behavior(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tax_behavior.toString());
	}

	/**
	 * Set value of Tax_behavior
	 * @param tax_behavior
	 */
	public final void setTax_behavior(java.lang.String tax_behavior)
	{
		setTax_behavior(getContext(), tax_behavior);
	}

	/**
	 * Set value of Tax_behavior
	 * @param context
	 * @param tax_behavior
	 */
	public final void setTax_behavior(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tax_behavior)
	{
		getMendixObject().setValue(context, MemberNames.Tax_behavior.toString(), tax_behavior);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Unit_amount
	 */
	public final java.lang.Integer getUnit_amount()
	{
		return getUnit_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_amount
	 */
	public final java.lang.Integer getUnit_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Unit_amount.toString());
	}

	/**
	 * Set value of Unit_amount
	 * @param unit_amount
	 */
	public final void setUnit_amount(java.lang.Integer unit_amount)
	{
		setUnit_amount(getContext(), unit_amount);
	}

	/**
	 * Set value of Unit_amount
	 * @param context
	 * @param unit_amount
	 */
	public final void setUnit_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer unit_amount)
	{
		getMendixObject().setValue(context, MemberNames.Unit_amount.toString(), unit_amount);
	}

	/**
	 * @return value of Unit_amount_decimal
	 */
	public final java.lang.String getUnit_amount_decimal()
	{
		return getUnit_amount_decimal(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_amount_decimal
	 */
	public final java.lang.String getUnit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit_amount_decimal.toString());
	}

	/**
	 * Set value of Unit_amount_decimal
	 * @param unit_amount_decimal
	 */
	public final void setUnit_amount_decimal(java.lang.String unit_amount_decimal)
	{
		setUnit_amount_decimal(getContext(), unit_amount_decimal);
	}

	/**
	 * Set value of Unit_amount_decimal
	 * @param context
	 * @param unit_amount_decimal
	 */
	public final void setUnit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit_amount_decimal)
	{
		getMendixObject().setValue(context, MemberNames.Unit_amount_decimal.toString(), unit_amount_decimal);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Root getInvoiceLineItem_Price_InvoiceLineItem_Root() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Price_InvoiceLineItem_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Root getInvoiceLineItem_Price_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @param invoicelineitem_price_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Price_InvoiceLineItem_Root(paymentgatewaystripe.proxies.InvoiceLineItem_Root invoicelineitem_price_invoicelineitem_root)
	{
		setInvoiceLineItem_Price_InvoiceLineItem_Root(getContext(), invoicelineitem_price_invoicelineitem_root);
	}

	/**
	 * Set value of InvoiceLineItem_Price_InvoiceLineItem_Root
	 * @param context
	 * @param invoicelineitem_price_invoicelineitem_root
	 */
	public final void setInvoiceLineItem_Price_InvoiceLineItem_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Root invoicelineitem_price_invoicelineitem_root)
	{
		if (invoicelineitem_price_invoicelineitem_root == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Price_InvoiceLineItem_Root.toString(), invoicelineitem_price_invoicelineitem_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvoiceLineItem_Metadata_2_InvoiceLineItem_Price
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2 getInvoiceLineItem_Metadata_2_InvoiceLineItem_Price() throws com.mendix.core.CoreException
	{
		return getInvoiceLineItem_Metadata_2_InvoiceLineItem_Price(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceLineItem_Metadata_2_InvoiceLineItem_Price
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2 getInvoiceLineItem_Metadata_2_InvoiceLineItem_Price(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvoiceLineItem_Metadata_2_InvoiceLineItem_Price.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvoiceLineItem_Metadata_2_InvoiceLineItem_Price
	 * @param invoicelineitem_metadata_2_invoicelineitem_price
	 */
	public final void setInvoiceLineItem_Metadata_2_InvoiceLineItem_Price(paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2 invoicelineitem_metadata_2_invoicelineitem_price)
	{
		setInvoiceLineItem_Metadata_2_InvoiceLineItem_Price(getContext(), invoicelineitem_metadata_2_invoicelineitem_price);
	}

	/**
	 * Set value of InvoiceLineItem_Metadata_2_InvoiceLineItem_Price
	 * @param context
	 * @param invoicelineitem_metadata_2_invoicelineitem_price
	 */
	public final void setInvoiceLineItem_Metadata_2_InvoiceLineItem_Price(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.InvoiceLineItem_Metadata_2 invoicelineitem_metadata_2_invoicelineitem_price)
	{
		if (invoicelineitem_metadata_2_invoicelineitem_price == null) {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Metadata_2_InvoiceLineItem_Price.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvoiceLineItem_Metadata_2_InvoiceLineItem_Price.toString(), invoicelineitem_metadata_2_invoicelineitem_price.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return invoiceLineItem_PriceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.InvoiceLineItem_Price that = (paymentgatewaystripe.proxies.InvoiceLineItem_Price) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
