// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Active("Active"),
		Created("Created"),
		Default_price("Default_price"),
		Description("Description"),
		Livemode("Livemode"),
		Name("Name"),
		Package_dimensions("Package_dimensions"),
		Statement_descriptor("Statement_descriptor"),
		Tax_code("Tax_code"),
		_type("_type"),
		Unit_label("Unit_label"),
		Updated("Updated"),
		Url("Url"),
		JsonObject_Data("PaymentGatewayStripe.JsonObject_Data"),
		Attributes_JsonObject("PaymentGatewayStripe.Attributes_JsonObject"),
		Images_JsonObject("PaymentGatewayStripe.Images_JsonObject"),
		Metadata_JsonObject("PaymentGatewayStripe.Metadata_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, jsonObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.JsonObject(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Default_price
	 */
	public final java.lang.String getDefault_price()
	{
		return getDefault_price(getContext());
	}

	/**
	 * @param context
	 * @return value of Default_price
	 */
	public final java.lang.String getDefault_price(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Default_price.toString());
	}

	/**
	 * Set value of Default_price
	 * @param default_price
	 */
	public final void setDefault_price(java.lang.String default_price)
	{
		setDefault_price(getContext(), default_price);
	}

	/**
	 * Set value of Default_price
	 * @param context
	 * @param default_price
	 */
	public final void setDefault_price(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String default_price)
	{
		getMendixObject().setValue(context, MemberNames.Default_price.toString(), default_price);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Package_dimensions
	 */
	public final java.lang.String getPackage_dimensions()
	{
		return getPackage_dimensions(getContext());
	}

	/**
	 * @param context
	 * @return value of Package_dimensions
	 */
	public final java.lang.String getPackage_dimensions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Package_dimensions.toString());
	}

	/**
	 * Set value of Package_dimensions
	 * @param package_dimensions
	 */
	public final void setPackage_dimensions(java.lang.String package_dimensions)
	{
		setPackage_dimensions(getContext(), package_dimensions);
	}

	/**
	 * Set value of Package_dimensions
	 * @param context
	 * @param package_dimensions
	 */
	public final void setPackage_dimensions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String package_dimensions)
	{
		getMendixObject().setValue(context, MemberNames.Package_dimensions.toString(), package_dimensions);
	}

	/**
	 * @return value of Statement_descriptor
	 */
	public final java.lang.String getStatement_descriptor()
	{
		return getStatement_descriptor(getContext());
	}

	/**
	 * @param context
	 * @return value of Statement_descriptor
	 */
	public final java.lang.String getStatement_descriptor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Statement_descriptor.toString());
	}

	/**
	 * Set value of Statement_descriptor
	 * @param statement_descriptor
	 */
	public final void setStatement_descriptor(java.lang.String statement_descriptor)
	{
		setStatement_descriptor(getContext(), statement_descriptor);
	}

	/**
	 * Set value of Statement_descriptor
	 * @param context
	 * @param statement_descriptor
	 */
	public final void setStatement_descriptor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statement_descriptor)
	{
		getMendixObject().setValue(context, MemberNames.Statement_descriptor.toString(), statement_descriptor);
	}

	/**
	 * @return value of Tax_code
	 */
	public final java.lang.String getTax_code()
	{
		return getTax_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Tax_code
	 */
	public final java.lang.String getTax_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tax_code.toString());
	}

	/**
	 * Set value of Tax_code
	 * @param tax_code
	 */
	public final void setTax_code(java.lang.String tax_code)
	{
		setTax_code(getContext(), tax_code);
	}

	/**
	 * Set value of Tax_code
	 * @param context
	 * @param tax_code
	 */
	public final void setTax_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tax_code)
	{
		getMendixObject().setValue(context, MemberNames.Tax_code.toString(), tax_code);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Unit_label
	 */
	public final java.lang.String getUnit_label()
	{
		return getUnit_label(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_label
	 */
	public final java.lang.String getUnit_label(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit_label.toString());
	}

	/**
	 * Set value of Unit_label
	 * @param unit_label
	 */
	public final void setUnit_label(java.lang.String unit_label)
	{
		setUnit_label(getContext(), unit_label);
	}

	/**
	 * Set value of Unit_label
	 * @param context
	 * @param unit_label
	 */
	public final void setUnit_label(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit_label)
	{
		getMendixObject().setValue(context, MemberNames.Unit_label.toString(), unit_label);
	}

	/**
	 * @return value of Updated
	 */
	public final java.lang.Integer getUpdated()
	{
		return getUpdated(getContext());
	}

	/**
	 * @param context
	 * @return value of Updated
	 */
	public final java.lang.Integer getUpdated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Updated.toString());
	}

	/**
	 * Set value of Updated
	 * @param updated
	 */
	public final void setUpdated(java.lang.Integer updated)
	{
		setUpdated(getContext(), updated);
	}

	/**
	 * Set value of Updated
	 * @param context
	 * @param updated
	 */
	public final void setUpdated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer updated)
	{
		getMendixObject().setValue(context, MemberNames.Updated.toString(), updated);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Data
	 */
	public final paymentgatewaystripe.proxies.Data getJsonObject_Data() throws com.mendix.core.CoreException
	{
		return getJsonObject_Data(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Data
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Data getJsonObject_Data(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Data.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Data.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Data
	 * @param jsonobject_data
	 */
	public final void setJsonObject_Data(paymentgatewaystripe.proxies.Data jsonobject_data)
	{
		setJsonObject_Data(getContext(), jsonobject_data);
	}

	/**
	 * Set value of JsonObject_Data
	 * @param context
	 * @param jsonobject_data
	 */
	public final void setJsonObject_Data(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Data jsonobject_data)
	{
		if (jsonobject_data == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Data.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Data.toString(), jsonobject_data.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Attributes_JsonObject
	 */
	public final paymentgatewaystripe.proxies.Attributes getAttributes_JsonObject() throws com.mendix.core.CoreException
	{
		return getAttributes_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Attributes_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Attributes getAttributes_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Attributes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attributes_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Attributes.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Attributes_JsonObject
	 * @param attributes_jsonobject
	 */
	public final void setAttributes_JsonObject(paymentgatewaystripe.proxies.Attributes attributes_jsonobject)
	{
		setAttributes_JsonObject(getContext(), attributes_jsonobject);
	}

	/**
	 * Set value of Attributes_JsonObject
	 * @param context
	 * @param attributes_jsonobject
	 */
	public final void setAttributes_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Attributes attributes_jsonobject)
	{
		if (attributes_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Attributes_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Attributes_JsonObject.toString(), attributes_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Images_JsonObject
	 */
	public final paymentgatewaystripe.proxies.Images getImages_JsonObject() throws com.mendix.core.CoreException
	{
		return getImages_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Images_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Images getImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Images result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Images_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Images.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Images_JsonObject
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(paymentgatewaystripe.proxies.Images images_jsonobject)
	{
		setImages_JsonObject(getContext(), images_jsonobject);
	}

	/**
	 * Set value of Images_JsonObject
	 * @param context
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Images images_jsonobject)
	{
		if (images_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), images_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Metadata_JsonObject
	 */
	public final paymentgatewaystripe.proxies.Metadata getMetadata_JsonObject() throws com.mendix.core.CoreException
	{
		return getMetadata_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Metadata_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.Metadata getMetadata_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.Metadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Metadata_JsonObject.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.Metadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Metadata_JsonObject
	 * @param metadata_jsonobject
	 */
	public final void setMetadata_JsonObject(paymentgatewaystripe.proxies.Metadata metadata_jsonobject)
	{
		setMetadata_JsonObject(getContext(), metadata_jsonobject);
	}

	/**
	 * Set value of Metadata_JsonObject
	 * @param context
	 * @param metadata_jsonobject
	 */
	public final void setMetadata_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.Metadata metadata_jsonobject)
	{
		if (metadata_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Metadata_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Metadata_JsonObject.toString(), metadata_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.JsonObject that = (paymentgatewaystripe.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
