// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class PaymentLink_Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentLink_RootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.PaymentLink_Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		_object("_object"),
		Active("Active"),
		Allow_promotion_codes("Allow_promotion_codes"),
		Billing_address_collection("Billing_address_collection"),
		Currency("Currency"),
		Customer_creation("Customer_creation"),
		Livemode("Livemode"),
		Payment_method_collection("Payment_method_collection"),
		Submit_type("Submit_type"),
		Url("Url"),
		PaymentLink_After_completion_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_After_completion_PaymentLink_Root"),
		PaymentLink_Automatic_tax_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_Automatic_tax_PaymentLink_Root"),
		PaymentLink_Metadata_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_Metadata_PaymentLink_Root"),
		PaymentLink_Phone_number_collection_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_Phone_number_collection_PaymentLink_Root"),
		PaymentLink_Shipping_options_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_Shipping_options_PaymentLink_Root"),
		PaymentLink_Tax_id_collection_PaymentLink_Root("PaymentGatewayStripe.PaymentLink_Tax_id_collection_PaymentLink_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentLink_RootMendixObject)
	{
		if (paymentLink_RootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, paymentLink_RootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.paymentLink_RootMendixObject = paymentLink_RootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PaymentLink_Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.PaymentLink_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.PaymentLink_Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.PaymentLink_Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.PaymentLink_Root(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.PaymentLink_Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.PaymentLink_Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of Allow_promotion_codes
	 */
	public final java.lang.Boolean getAllow_promotion_codes()
	{
		return getAllow_promotion_codes(getContext());
	}

	/**
	 * @param context
	 * @return value of Allow_promotion_codes
	 */
	public final java.lang.Boolean getAllow_promotion_codes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Allow_promotion_codes.toString());
	}

	/**
	 * Set value of Allow_promotion_codes
	 * @param allow_promotion_codes
	 */
	public final void setAllow_promotion_codes(java.lang.Boolean allow_promotion_codes)
	{
		setAllow_promotion_codes(getContext(), allow_promotion_codes);
	}

	/**
	 * Set value of Allow_promotion_codes
	 * @param context
	 * @param allow_promotion_codes
	 */
	public final void setAllow_promotion_codes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allow_promotion_codes)
	{
		getMendixObject().setValue(context, MemberNames.Allow_promotion_codes.toString(), allow_promotion_codes);
	}

	/**
	 * @return value of Billing_address_collection
	 */
	public final java.lang.String getBilling_address_collection()
	{
		return getBilling_address_collection(getContext());
	}

	/**
	 * @param context
	 * @return value of Billing_address_collection
	 */
	public final java.lang.String getBilling_address_collection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Billing_address_collection.toString());
	}

	/**
	 * Set value of Billing_address_collection
	 * @param billing_address_collection
	 */
	public final void setBilling_address_collection(java.lang.String billing_address_collection)
	{
		setBilling_address_collection(getContext(), billing_address_collection);
	}

	/**
	 * Set value of Billing_address_collection
	 * @param context
	 * @param billing_address_collection
	 */
	public final void setBilling_address_collection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billing_address_collection)
	{
		getMendixObject().setValue(context, MemberNames.Billing_address_collection.toString(), billing_address_collection);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Customer_creation
	 */
	public final java.lang.String getCustomer_creation()
	{
		return getCustomer_creation(getContext());
	}

	/**
	 * @param context
	 * @return value of Customer_creation
	 */
	public final java.lang.String getCustomer_creation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Customer_creation.toString());
	}

	/**
	 * Set value of Customer_creation
	 * @param customer_creation
	 */
	public final void setCustomer_creation(java.lang.String customer_creation)
	{
		setCustomer_creation(getContext(), customer_creation);
	}

	/**
	 * Set value of Customer_creation
	 * @param context
	 * @param customer_creation
	 */
	public final void setCustomer_creation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customer_creation)
	{
		getMendixObject().setValue(context, MemberNames.Customer_creation.toString(), customer_creation);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Payment_method_collection
	 */
	public final java.lang.String getPayment_method_collection()
	{
		return getPayment_method_collection(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_method_collection
	 */
	public final java.lang.String getPayment_method_collection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payment_method_collection.toString());
	}

	/**
	 * Set value of Payment_method_collection
	 * @param payment_method_collection
	 */
	public final void setPayment_method_collection(java.lang.String payment_method_collection)
	{
		setPayment_method_collection(getContext(), payment_method_collection);
	}

	/**
	 * Set value of Payment_method_collection
	 * @param context
	 * @param payment_method_collection
	 */
	public final void setPayment_method_collection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payment_method_collection)
	{
		getMendixObject().setValue(context, MemberNames.Payment_method_collection.toString(), payment_method_collection);
	}

	/**
	 * @return value of Submit_type
	 */
	public final java.lang.String getSubmit_type()
	{
		return getSubmit_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Submit_type
	 */
	public final java.lang.String getSubmit_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Submit_type.toString());
	}

	/**
	 * Set value of Submit_type
	 * @param submit_type
	 */
	public final void setSubmit_type(java.lang.String submit_type)
	{
		setSubmit_type(getContext(), submit_type);
	}

	/**
	 * Set value of Submit_type
	 * @param context
	 * @param submit_type
	 */
	public final void setSubmit_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String submit_type)
	{
		getMendixObject().setValue(context, MemberNames.Submit_type.toString(), submit_type);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_After_completion_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_After_completion getPaymentLink_After_completion_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_After_completion_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_After_completion_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_After_completion getPaymentLink_After_completion_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_After_completion result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_After_completion_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_After_completion.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_After_completion_PaymentLink_Root
	 * @param paymentlink_after_completion_paymentlink_root
	 */
	public final void setPaymentLink_After_completion_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_After_completion paymentlink_after_completion_paymentlink_root)
	{
		setPaymentLink_After_completion_PaymentLink_Root(getContext(), paymentlink_after_completion_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_After_completion_PaymentLink_Root
	 * @param context
	 * @param paymentlink_after_completion_paymentlink_root
	 */
	public final void setPaymentLink_After_completion_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_After_completion paymentlink_after_completion_paymentlink_root)
	{
		if (paymentlink_after_completion_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_After_completion_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_After_completion_PaymentLink_Root.toString(), paymentlink_after_completion_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_Automatic_tax_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Automatic_tax getPaymentLink_Automatic_tax_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_Automatic_tax_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_Automatic_tax_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Automatic_tax getPaymentLink_Automatic_tax_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_Automatic_tax result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_Automatic_tax_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_Automatic_tax.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_Automatic_tax_PaymentLink_Root
	 * @param paymentlink_automatic_tax_paymentlink_root
	 */
	public final void setPaymentLink_Automatic_tax_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_Automatic_tax paymentlink_automatic_tax_paymentlink_root)
	{
		setPaymentLink_Automatic_tax_PaymentLink_Root(getContext(), paymentlink_automatic_tax_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_Automatic_tax_PaymentLink_Root
	 * @param context
	 * @param paymentlink_automatic_tax_paymentlink_root
	 */
	public final void setPaymentLink_Automatic_tax_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_Automatic_tax paymentlink_automatic_tax_paymentlink_root)
	{
		if (paymentlink_automatic_tax_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Automatic_tax_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Automatic_tax_PaymentLink_Root.toString(), paymentlink_automatic_tax_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_Metadata_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Metadata getPaymentLink_Metadata_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_Metadata_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_Metadata_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Metadata getPaymentLink_Metadata_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_Metadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_Metadata_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_Metadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_Metadata_PaymentLink_Root
	 * @param paymentlink_metadata_paymentlink_root
	 */
	public final void setPaymentLink_Metadata_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_Metadata paymentlink_metadata_paymentlink_root)
	{
		setPaymentLink_Metadata_PaymentLink_Root(getContext(), paymentlink_metadata_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_Metadata_PaymentLink_Root
	 * @param context
	 * @param paymentlink_metadata_paymentlink_root
	 */
	public final void setPaymentLink_Metadata_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_Metadata paymentlink_metadata_paymentlink_root)
	{
		if (paymentlink_metadata_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Metadata_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Metadata_PaymentLink_Root.toString(), paymentlink_metadata_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_Phone_number_collection_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection getPaymentLink_Phone_number_collection_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_Phone_number_collection_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_Phone_number_collection_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection getPaymentLink_Phone_number_collection_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_Phone_number_collection_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_Phone_number_collection_PaymentLink_Root
	 * @param paymentlink_phone_number_collection_paymentlink_root
	 */
	public final void setPaymentLink_Phone_number_collection_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection paymentlink_phone_number_collection_paymentlink_root)
	{
		setPaymentLink_Phone_number_collection_PaymentLink_Root(getContext(), paymentlink_phone_number_collection_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_Phone_number_collection_PaymentLink_Root
	 * @param context
	 * @param paymentlink_phone_number_collection_paymentlink_root
	 */
	public final void setPaymentLink_Phone_number_collection_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_Phone_number_collection paymentlink_phone_number_collection_paymentlink_root)
	{
		if (paymentlink_phone_number_collection_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Phone_number_collection_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Phone_number_collection_PaymentLink_Root.toString(), paymentlink_phone_number_collection_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_Shipping_options_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Shipping_options getPaymentLink_Shipping_options_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_Shipping_options_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_Shipping_options_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Shipping_options getPaymentLink_Shipping_options_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_Shipping_options result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_Shipping_options_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_Shipping_options.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_Shipping_options_PaymentLink_Root
	 * @param paymentlink_shipping_options_paymentlink_root
	 */
	public final void setPaymentLink_Shipping_options_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_Shipping_options paymentlink_shipping_options_paymentlink_root)
	{
		setPaymentLink_Shipping_options_PaymentLink_Root(getContext(), paymentlink_shipping_options_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_Shipping_options_PaymentLink_Root
	 * @param context
	 * @param paymentlink_shipping_options_paymentlink_root
	 */
	public final void setPaymentLink_Shipping_options_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_Shipping_options paymentlink_shipping_options_paymentlink_root)
	{
		if (paymentlink_shipping_options_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Shipping_options_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Shipping_options_PaymentLink_Root.toString(), paymentlink_shipping_options_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentLink_Tax_id_collection_PaymentLink_Root
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection getPaymentLink_Tax_id_collection_PaymentLink_Root() throws com.mendix.core.CoreException
	{
		return getPaymentLink_Tax_id_collection_PaymentLink_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentLink_Tax_id_collection_PaymentLink_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection getPaymentLink_Tax_id_collection_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentLink_Tax_id_collection_PaymentLink_Root.toString());
		if (identifier != null) {
			result = paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentLink_Tax_id_collection_PaymentLink_Root
	 * @param paymentlink_tax_id_collection_paymentlink_root
	 */
	public final void setPaymentLink_Tax_id_collection_PaymentLink_Root(paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection paymentlink_tax_id_collection_paymentlink_root)
	{
		setPaymentLink_Tax_id_collection_PaymentLink_Root(getContext(), paymentlink_tax_id_collection_paymentlink_root);
	}

	/**
	 * Set value of PaymentLink_Tax_id_collection_PaymentLink_Root
	 * @param context
	 * @param paymentlink_tax_id_collection_paymentlink_root
	 */
	public final void setPaymentLink_Tax_id_collection_PaymentLink_Root(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.PaymentLink_Tax_id_collection paymentlink_tax_id_collection_paymentlink_root)
	{
		if (paymentlink_tax_id_collection_paymentlink_root == null) {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Tax_id_collection_PaymentLink_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentLink_Tax_id_collection_PaymentLink_Root.toString(), paymentlink_tax_id_collection_paymentlink_root.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentLink_RootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.PaymentLink_Root that = (paymentgatewaystripe.proxies.PaymentLink_Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
