// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies;

public class PriceAPI
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject priceAPIMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PaymentGatewayStripe.PriceAPI";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		currency("currency"),
		productid("productid"),
		unit_type("unit_type"),
		unit_amount("unit_amount"),
		unit_amount_decimal("unit_amount_decimal"),
		active("active"),
		billing_scheme("billing_scheme"),
		custom_unit_amount_enabled("custom_unit_amount_enabled"),
		custom_unit_amount_maximum("custom_unit_amount_maximum"),
		custom_unit_amount_minimum("custom_unit_amount_minimum"),
		custom_unit_amount_preset("custom_unit_amount_preset"),
		lookup_key("lookup_key"),
		nickname("nickname"),
		product_data_name("product_data_name"),
		product_data_active("product_data_active"),
		product_data_id("product_data_id"),
		product_data_statement_descriptor("product_data_statement_descriptor"),
		product_data_tax_code("product_data_tax_code"),
		product_data_unit_label("product_data_unit_label"),
		recurring_interval("recurring_interval"),
		recurring_aggregate_usage("recurring_aggregate_usage"),
		recurring_interval_count("recurring_interval_count"),
		recurring_usage_type("recurring_usage_type"),
		tax_behavior("tax_behavior"),
		tiers_mode("tiers_mode"),
		transfer_lookup_key("transfer_lookup_key"),
		transform_quantity_divide_by("transform_quantity_divide_by"),
		CreateProduct("CreateProduct"),
		transform_quantity_round("transform_quantity_round"),
		_id("_id"),
		_object("_object"),
		Created("Created"),
		Livemode("Livemode"),
		Product("Product"),
		_type("_type"),
		Unit_Amount_String("Unit_Amount_String");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PriceAPI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PriceAPI(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject priceAPIMendixObject)
	{
		if (priceAPIMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, priceAPIMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.priceAPIMendixObject = priceAPIMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PriceAPI.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static paymentgatewaystripe.proxies.PriceAPI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return paymentgatewaystripe.proxies.PriceAPI.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static paymentgatewaystripe.proxies.PriceAPI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new paymentgatewaystripe.proxies.PriceAPI(context, mendixObject);
	}

	public static paymentgatewaystripe.proxies.PriceAPI load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return paymentgatewaystripe.proxies.PriceAPI.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of currency
	 */
	public final java.lang.String getcurrency()
	{
		return getcurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of currency
	 */
	public final java.lang.String getcurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.currency.toString());
	}

	/**
	 * Set value of currency
	 * @param currency
	 */
	public final void setcurrency(java.lang.String currency)
	{
		setcurrency(getContext(), currency);
	}

	/**
	 * Set value of currency
	 * @param context
	 * @param currency
	 */
	public final void setcurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.currency.toString(), currency);
	}

	/**
	 * @return value of productid
	 */
	public final java.lang.String getproductid()
	{
		return getproductid(getContext());
	}

	/**
	 * @param context
	 * @return value of productid
	 */
	public final java.lang.String getproductid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.productid.toString());
	}

	/**
	 * Set value of productid
	 * @param productid
	 */
	public final void setproductid(java.lang.String productid)
	{
		setproductid(getContext(), productid);
	}

	/**
	 * Set value of productid
	 * @param context
	 * @param productid
	 */
	public final void setproductid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productid)
	{
		getMendixObject().setValue(context, MemberNames.productid.toString(), productid);
	}

	/**
	 * Set value of unit_type
	 * @param unit_type
	 */
	public final paymentgatewaystripe.proxies.ENUM_PriceUnitType getunit_type()
	{
		return getunit_type(getContext());
	}

	/**
	 * @param context
	 * @return value of unit_type
	 */
	public final paymentgatewaystripe.proxies.ENUM_PriceUnitType getunit_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.unit_type.toString());
		if (obj == null) {
			return null;
		}
		return paymentgatewaystripe.proxies.ENUM_PriceUnitType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of unit_type
	 * @param unit_type
	 */
	public final void setunit_type(paymentgatewaystripe.proxies.ENUM_PriceUnitType unit_type)
	{
		setunit_type(getContext(), unit_type);
	}

	/**
	 * Set value of unit_type
	 * @param context
	 * @param unit_type
	 */
	public final void setunit_type(com.mendix.systemwideinterfaces.core.IContext context, paymentgatewaystripe.proxies.ENUM_PriceUnitType unit_type)
	{
		if (unit_type != null) {
			getMendixObject().setValue(context, MemberNames.unit_type.toString(), unit_type.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.unit_type.toString(), null);
		}
	}

	/**
	 * @return value of unit_amount
	 */
	public final java.lang.Integer getunit_amount()
	{
		return getunit_amount(getContext());
	}

	/**
	 * @param context
	 * @return value of unit_amount
	 */
	public final java.lang.Integer getunit_amount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.unit_amount.toString());
	}

	/**
	 * Set value of unit_amount
	 * @param unit_amount
	 */
	public final void setunit_amount(java.lang.Integer unit_amount)
	{
		setunit_amount(getContext(), unit_amount);
	}

	/**
	 * Set value of unit_amount
	 * @param context
	 * @param unit_amount
	 */
	public final void setunit_amount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer unit_amount)
	{
		getMendixObject().setValue(context, MemberNames.unit_amount.toString(), unit_amount);
	}

	/**
	 * @return value of unit_amount_decimal
	 */
	public final java.math.BigDecimal getunit_amount_decimal()
	{
		return getunit_amount_decimal(getContext());
	}

	/**
	 * @param context
	 * @return value of unit_amount_decimal
	 */
	public final java.math.BigDecimal getunit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.unit_amount_decimal.toString());
	}

	/**
	 * Set value of unit_amount_decimal
	 * @param unit_amount_decimal
	 */
	public final void setunit_amount_decimal(java.math.BigDecimal unit_amount_decimal)
	{
		setunit_amount_decimal(getContext(), unit_amount_decimal);
	}

	/**
	 * Set value of unit_amount_decimal
	 * @param context
	 * @param unit_amount_decimal
	 */
	public final void setunit_amount_decimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal unit_amount_decimal)
	{
		getMendixObject().setValue(context, MemberNames.unit_amount_decimal.toString(), unit_amount_decimal);
	}

	/**
	 * @return value of active
	 */
	public final java.lang.Boolean getactive()
	{
		return getactive(getContext());
	}

	/**
	 * @param context
	 * @return value of active
	 */
	public final java.lang.Boolean getactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.active.toString());
	}

	/**
	 * Set value of active
	 * @param active
	 */
	public final void setactive(java.lang.Boolean active)
	{
		setactive(getContext(), active);
	}

	/**
	 * Set value of active
	 * @param context
	 * @param active
	 */
	public final void setactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.active.toString(), active);
	}

	/**
	 * @return value of billing_scheme
	 */
	public final java.lang.String getbilling_scheme()
	{
		return getbilling_scheme(getContext());
	}

	/**
	 * @param context
	 * @return value of billing_scheme
	 */
	public final java.lang.String getbilling_scheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.billing_scheme.toString());
	}

	/**
	 * Set value of billing_scheme
	 * @param billing_scheme
	 */
	public final void setbilling_scheme(java.lang.String billing_scheme)
	{
		setbilling_scheme(getContext(), billing_scheme);
	}

	/**
	 * Set value of billing_scheme
	 * @param context
	 * @param billing_scheme
	 */
	public final void setbilling_scheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billing_scheme)
	{
		getMendixObject().setValue(context, MemberNames.billing_scheme.toString(), billing_scheme);
	}

	/**
	 * @return value of custom_unit_amount_enabled
	 */
	public final java.lang.Boolean getcustom_unit_amount_enabled()
	{
		return getcustom_unit_amount_enabled(getContext());
	}

	/**
	 * @param context
	 * @return value of custom_unit_amount_enabled
	 */
	public final java.lang.Boolean getcustom_unit_amount_enabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.custom_unit_amount_enabled.toString());
	}

	/**
	 * Set value of custom_unit_amount_enabled
	 * @param custom_unit_amount_enabled
	 */
	public final void setcustom_unit_amount_enabled(java.lang.Boolean custom_unit_amount_enabled)
	{
		setcustom_unit_amount_enabled(getContext(), custom_unit_amount_enabled);
	}

	/**
	 * Set value of custom_unit_amount_enabled
	 * @param context
	 * @param custom_unit_amount_enabled
	 */
	public final void setcustom_unit_amount_enabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean custom_unit_amount_enabled)
	{
		getMendixObject().setValue(context, MemberNames.custom_unit_amount_enabled.toString(), custom_unit_amount_enabled);
	}

	/**
	 * @return value of custom_unit_amount_maximum
	 */
	public final java.lang.Integer getcustom_unit_amount_maximum()
	{
		return getcustom_unit_amount_maximum(getContext());
	}

	/**
	 * @param context
	 * @return value of custom_unit_amount_maximum
	 */
	public final java.lang.Integer getcustom_unit_amount_maximum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.custom_unit_amount_maximum.toString());
	}

	/**
	 * Set value of custom_unit_amount_maximum
	 * @param custom_unit_amount_maximum
	 */
	public final void setcustom_unit_amount_maximum(java.lang.Integer custom_unit_amount_maximum)
	{
		setcustom_unit_amount_maximum(getContext(), custom_unit_amount_maximum);
	}

	/**
	 * Set value of custom_unit_amount_maximum
	 * @param context
	 * @param custom_unit_amount_maximum
	 */
	public final void setcustom_unit_amount_maximum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer custom_unit_amount_maximum)
	{
		getMendixObject().setValue(context, MemberNames.custom_unit_amount_maximum.toString(), custom_unit_amount_maximum);
	}

	/**
	 * @return value of custom_unit_amount_minimum
	 */
	public final java.lang.Integer getcustom_unit_amount_minimum()
	{
		return getcustom_unit_amount_minimum(getContext());
	}

	/**
	 * @param context
	 * @return value of custom_unit_amount_minimum
	 */
	public final java.lang.Integer getcustom_unit_amount_minimum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.custom_unit_amount_minimum.toString());
	}

	/**
	 * Set value of custom_unit_amount_minimum
	 * @param custom_unit_amount_minimum
	 */
	public final void setcustom_unit_amount_minimum(java.lang.Integer custom_unit_amount_minimum)
	{
		setcustom_unit_amount_minimum(getContext(), custom_unit_amount_minimum);
	}

	/**
	 * Set value of custom_unit_amount_minimum
	 * @param context
	 * @param custom_unit_amount_minimum
	 */
	public final void setcustom_unit_amount_minimum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer custom_unit_amount_minimum)
	{
		getMendixObject().setValue(context, MemberNames.custom_unit_amount_minimum.toString(), custom_unit_amount_minimum);
	}

	/**
	 * @return value of custom_unit_amount_preset
	 */
	public final java.lang.Integer getcustom_unit_amount_preset()
	{
		return getcustom_unit_amount_preset(getContext());
	}

	/**
	 * @param context
	 * @return value of custom_unit_amount_preset
	 */
	public final java.lang.Integer getcustom_unit_amount_preset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.custom_unit_amount_preset.toString());
	}

	/**
	 * Set value of custom_unit_amount_preset
	 * @param custom_unit_amount_preset
	 */
	public final void setcustom_unit_amount_preset(java.lang.Integer custom_unit_amount_preset)
	{
		setcustom_unit_amount_preset(getContext(), custom_unit_amount_preset);
	}

	/**
	 * Set value of custom_unit_amount_preset
	 * @param context
	 * @param custom_unit_amount_preset
	 */
	public final void setcustom_unit_amount_preset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer custom_unit_amount_preset)
	{
		getMendixObject().setValue(context, MemberNames.custom_unit_amount_preset.toString(), custom_unit_amount_preset);
	}

	/**
	 * @return value of lookup_key
	 */
	public final java.lang.String getlookup_key()
	{
		return getlookup_key(getContext());
	}

	/**
	 * @param context
	 * @return value of lookup_key
	 */
	public final java.lang.String getlookup_key(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.lookup_key.toString());
	}

	/**
	 * Set value of lookup_key
	 * @param lookup_key
	 */
	public final void setlookup_key(java.lang.String lookup_key)
	{
		setlookup_key(getContext(), lookup_key);
	}

	/**
	 * Set value of lookup_key
	 * @param context
	 * @param lookup_key
	 */
	public final void setlookup_key(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lookup_key)
	{
		getMendixObject().setValue(context, MemberNames.lookup_key.toString(), lookup_key);
	}

	/**
	 * @return value of nickname
	 */
	public final java.lang.String getnickname()
	{
		return getnickname(getContext());
	}

	/**
	 * @param context
	 * @return value of nickname
	 */
	public final java.lang.String getnickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nickname.toString());
	}

	/**
	 * Set value of nickname
	 * @param nickname
	 */
	public final void setnickname(java.lang.String nickname)
	{
		setnickname(getContext(), nickname);
	}

	/**
	 * Set value of nickname
	 * @param context
	 * @param nickname
	 */
	public final void setnickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nickname)
	{
		getMendixObject().setValue(context, MemberNames.nickname.toString(), nickname);
	}

	/**
	 * @return value of product_data_name
	 */
	public final java.lang.String getproduct_data_name()
	{
		return getproduct_data_name(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_name
	 */
	public final java.lang.String getproduct_data_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product_data_name.toString());
	}

	/**
	 * Set value of product_data_name
	 * @param product_data_name
	 */
	public final void setproduct_data_name(java.lang.String product_data_name)
	{
		setproduct_data_name(getContext(), product_data_name);
	}

	/**
	 * Set value of product_data_name
	 * @param context
	 * @param product_data_name
	 */
	public final void setproduct_data_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product_data_name)
	{
		getMendixObject().setValue(context, MemberNames.product_data_name.toString(), product_data_name);
	}

	/**
	 * @return value of product_data_active
	 */
	public final java.lang.Boolean getproduct_data_active()
	{
		return getproduct_data_active(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_active
	 */
	public final java.lang.Boolean getproduct_data_active(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.product_data_active.toString());
	}

	/**
	 * Set value of product_data_active
	 * @param product_data_active
	 */
	public final void setproduct_data_active(java.lang.Boolean product_data_active)
	{
		setproduct_data_active(getContext(), product_data_active);
	}

	/**
	 * Set value of product_data_active
	 * @param context
	 * @param product_data_active
	 */
	public final void setproduct_data_active(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean product_data_active)
	{
		getMendixObject().setValue(context, MemberNames.product_data_active.toString(), product_data_active);
	}

	/**
	 * @return value of product_data_id
	 */
	public final java.lang.String getproduct_data_id()
	{
		return getproduct_data_id(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_id
	 */
	public final java.lang.String getproduct_data_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product_data_id.toString());
	}

	/**
	 * Set value of product_data_id
	 * @param product_data_id
	 */
	public final void setproduct_data_id(java.lang.String product_data_id)
	{
		setproduct_data_id(getContext(), product_data_id);
	}

	/**
	 * Set value of product_data_id
	 * @param context
	 * @param product_data_id
	 */
	public final void setproduct_data_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product_data_id)
	{
		getMendixObject().setValue(context, MemberNames.product_data_id.toString(), product_data_id);
	}

	/**
	 * @return value of product_data_statement_descriptor
	 */
	public final java.lang.String getproduct_data_statement_descriptor()
	{
		return getproduct_data_statement_descriptor(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_statement_descriptor
	 */
	public final java.lang.String getproduct_data_statement_descriptor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product_data_statement_descriptor.toString());
	}

	/**
	 * Set value of product_data_statement_descriptor
	 * @param product_data_statement_descriptor
	 */
	public final void setproduct_data_statement_descriptor(java.lang.String product_data_statement_descriptor)
	{
		setproduct_data_statement_descriptor(getContext(), product_data_statement_descriptor);
	}

	/**
	 * Set value of product_data_statement_descriptor
	 * @param context
	 * @param product_data_statement_descriptor
	 */
	public final void setproduct_data_statement_descriptor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product_data_statement_descriptor)
	{
		getMendixObject().setValue(context, MemberNames.product_data_statement_descriptor.toString(), product_data_statement_descriptor);
	}

	/**
	 * @return value of product_data_tax_code
	 */
	public final java.lang.String getproduct_data_tax_code()
	{
		return getproduct_data_tax_code(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_tax_code
	 */
	public final java.lang.String getproduct_data_tax_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product_data_tax_code.toString());
	}

	/**
	 * Set value of product_data_tax_code
	 * @param product_data_tax_code
	 */
	public final void setproduct_data_tax_code(java.lang.String product_data_tax_code)
	{
		setproduct_data_tax_code(getContext(), product_data_tax_code);
	}

	/**
	 * Set value of product_data_tax_code
	 * @param context
	 * @param product_data_tax_code
	 */
	public final void setproduct_data_tax_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product_data_tax_code)
	{
		getMendixObject().setValue(context, MemberNames.product_data_tax_code.toString(), product_data_tax_code);
	}

	/**
	 * @return value of product_data_unit_label
	 */
	public final java.lang.String getproduct_data_unit_label()
	{
		return getproduct_data_unit_label(getContext());
	}

	/**
	 * @param context
	 * @return value of product_data_unit_label
	 */
	public final java.lang.String getproduct_data_unit_label(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product_data_unit_label.toString());
	}

	/**
	 * Set value of product_data_unit_label
	 * @param product_data_unit_label
	 */
	public final void setproduct_data_unit_label(java.lang.String product_data_unit_label)
	{
		setproduct_data_unit_label(getContext(), product_data_unit_label);
	}

	/**
	 * Set value of product_data_unit_label
	 * @param context
	 * @param product_data_unit_label
	 */
	public final void setproduct_data_unit_label(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product_data_unit_label)
	{
		getMendixObject().setValue(context, MemberNames.product_data_unit_label.toString(), product_data_unit_label);
	}

	/**
	 * @return value of recurring_interval
	 */
	public final java.lang.String getrecurring_interval()
	{
		return getrecurring_interval(getContext());
	}

	/**
	 * @param context
	 * @return value of recurring_interval
	 */
	public final java.lang.String getrecurring_interval(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recurring_interval.toString());
	}

	/**
	 * Set value of recurring_interval
	 * @param recurring_interval
	 */
	public final void setrecurring_interval(java.lang.String recurring_interval)
	{
		setrecurring_interval(getContext(), recurring_interval);
	}

	/**
	 * Set value of recurring_interval
	 * @param context
	 * @param recurring_interval
	 */
	public final void setrecurring_interval(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recurring_interval)
	{
		getMendixObject().setValue(context, MemberNames.recurring_interval.toString(), recurring_interval);
	}

	/**
	 * @return value of recurring_aggregate_usage
	 */
	public final java.lang.String getrecurring_aggregate_usage()
	{
		return getrecurring_aggregate_usage(getContext());
	}

	/**
	 * @param context
	 * @return value of recurring_aggregate_usage
	 */
	public final java.lang.String getrecurring_aggregate_usage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recurring_aggregate_usage.toString());
	}

	/**
	 * Set value of recurring_aggregate_usage
	 * @param recurring_aggregate_usage
	 */
	public final void setrecurring_aggregate_usage(java.lang.String recurring_aggregate_usage)
	{
		setrecurring_aggregate_usage(getContext(), recurring_aggregate_usage);
	}

	/**
	 * Set value of recurring_aggregate_usage
	 * @param context
	 * @param recurring_aggregate_usage
	 */
	public final void setrecurring_aggregate_usage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recurring_aggregate_usage)
	{
		getMendixObject().setValue(context, MemberNames.recurring_aggregate_usage.toString(), recurring_aggregate_usage);
	}

	/**
	 * @return value of recurring_interval_count
	 */
	public final java.lang.Integer getrecurring_interval_count()
	{
		return getrecurring_interval_count(getContext());
	}

	/**
	 * @param context
	 * @return value of recurring_interval_count
	 */
	public final java.lang.Integer getrecurring_interval_count(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.recurring_interval_count.toString());
	}

	/**
	 * Set value of recurring_interval_count
	 * @param recurring_interval_count
	 */
	public final void setrecurring_interval_count(java.lang.Integer recurring_interval_count)
	{
		setrecurring_interval_count(getContext(), recurring_interval_count);
	}

	/**
	 * Set value of recurring_interval_count
	 * @param context
	 * @param recurring_interval_count
	 */
	public final void setrecurring_interval_count(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer recurring_interval_count)
	{
		getMendixObject().setValue(context, MemberNames.recurring_interval_count.toString(), recurring_interval_count);
	}

	/**
	 * @return value of recurring_usage_type
	 */
	public final java.lang.String getrecurring_usage_type()
	{
		return getrecurring_usage_type(getContext());
	}

	/**
	 * @param context
	 * @return value of recurring_usage_type
	 */
	public final java.lang.String getrecurring_usage_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recurring_usage_type.toString());
	}

	/**
	 * Set value of recurring_usage_type
	 * @param recurring_usage_type
	 */
	public final void setrecurring_usage_type(java.lang.String recurring_usage_type)
	{
		setrecurring_usage_type(getContext(), recurring_usage_type);
	}

	/**
	 * Set value of recurring_usage_type
	 * @param context
	 * @param recurring_usage_type
	 */
	public final void setrecurring_usage_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recurring_usage_type)
	{
		getMendixObject().setValue(context, MemberNames.recurring_usage_type.toString(), recurring_usage_type);
	}

	/**
	 * @return value of tax_behavior
	 */
	public final java.lang.String gettax_behavior()
	{
		return gettax_behavior(getContext());
	}

	/**
	 * @param context
	 * @return value of tax_behavior
	 */
	public final java.lang.String gettax_behavior(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tax_behavior.toString());
	}

	/**
	 * Set value of tax_behavior
	 * @param tax_behavior
	 */
	public final void settax_behavior(java.lang.String tax_behavior)
	{
		settax_behavior(getContext(), tax_behavior);
	}

	/**
	 * Set value of tax_behavior
	 * @param context
	 * @param tax_behavior
	 */
	public final void settax_behavior(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tax_behavior)
	{
		getMendixObject().setValue(context, MemberNames.tax_behavior.toString(), tax_behavior);
	}

	/**
	 * @return value of tiers_mode
	 */
	public final java.lang.String gettiers_mode()
	{
		return gettiers_mode(getContext());
	}

	/**
	 * @param context
	 * @return value of tiers_mode
	 */
	public final java.lang.String gettiers_mode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tiers_mode.toString());
	}

	/**
	 * Set value of tiers_mode
	 * @param tiers_mode
	 */
	public final void settiers_mode(java.lang.String tiers_mode)
	{
		settiers_mode(getContext(), tiers_mode);
	}

	/**
	 * Set value of tiers_mode
	 * @param context
	 * @param tiers_mode
	 */
	public final void settiers_mode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tiers_mode)
	{
		getMendixObject().setValue(context, MemberNames.tiers_mode.toString(), tiers_mode);
	}

	/**
	 * @return value of transfer_lookup_key
	 */
	public final java.lang.Boolean gettransfer_lookup_key()
	{
		return gettransfer_lookup_key(getContext());
	}

	/**
	 * @param context
	 * @return value of transfer_lookup_key
	 */
	public final java.lang.Boolean gettransfer_lookup_key(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.transfer_lookup_key.toString());
	}

	/**
	 * Set value of transfer_lookup_key
	 * @param transfer_lookup_key
	 */
	public final void settransfer_lookup_key(java.lang.Boolean transfer_lookup_key)
	{
		settransfer_lookup_key(getContext(), transfer_lookup_key);
	}

	/**
	 * Set value of transfer_lookup_key
	 * @param context
	 * @param transfer_lookup_key
	 */
	public final void settransfer_lookup_key(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean transfer_lookup_key)
	{
		getMendixObject().setValue(context, MemberNames.transfer_lookup_key.toString(), transfer_lookup_key);
	}

	/**
	 * @return value of transform_quantity_divide_by
	 */
	public final java.lang.Integer gettransform_quantity_divide_by()
	{
		return gettransform_quantity_divide_by(getContext());
	}

	/**
	 * @param context
	 * @return value of transform_quantity_divide_by
	 */
	public final java.lang.Integer gettransform_quantity_divide_by(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.transform_quantity_divide_by.toString());
	}

	/**
	 * Set value of transform_quantity_divide_by
	 * @param transform_quantity_divide_by
	 */
	public final void settransform_quantity_divide_by(java.lang.Integer transform_quantity_divide_by)
	{
		settransform_quantity_divide_by(getContext(), transform_quantity_divide_by);
	}

	/**
	 * Set value of transform_quantity_divide_by
	 * @param context
	 * @param transform_quantity_divide_by
	 */
	public final void settransform_quantity_divide_by(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transform_quantity_divide_by)
	{
		getMendixObject().setValue(context, MemberNames.transform_quantity_divide_by.toString(), transform_quantity_divide_by);
	}

	/**
	 * @return value of CreateProduct
	 */
	public final java.lang.Boolean getCreateProduct()
	{
		return getCreateProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateProduct
	 */
	public final java.lang.Boolean getCreateProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CreateProduct.toString());
	}

	/**
	 * Set value of CreateProduct
	 * @param createproduct
	 */
	public final void setCreateProduct(java.lang.Boolean createproduct)
	{
		setCreateProduct(getContext(), createproduct);
	}

	/**
	 * Set value of CreateProduct
	 * @param context
	 * @param createproduct
	 */
	public final void setCreateProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean createproduct)
	{
		getMendixObject().setValue(context, MemberNames.CreateProduct.toString(), createproduct);
	}

	/**
	 * @return value of transform_quantity_round
	 */
	public final java.lang.String gettransform_quantity_round()
	{
		return gettransform_quantity_round(getContext());
	}

	/**
	 * @param context
	 * @return value of transform_quantity_round
	 */
	public final java.lang.String gettransform_quantity_round(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.transform_quantity_round.toString());
	}

	/**
	 * Set value of transform_quantity_round
	 * @param transform_quantity_round
	 */
	public final void settransform_quantity_round(java.lang.String transform_quantity_round)
	{
		settransform_quantity_round(getContext(), transform_quantity_round);
	}

	/**
	 * Set value of transform_quantity_round
	 * @param context
	 * @param transform_quantity_round
	 */
	public final void settransform_quantity_round(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transform_quantity_round)
	{
		getMendixObject().setValue(context, MemberNames.transform_quantity_round.toString(), transform_quantity_round);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of _object
	 */
	public final java.lang.String get_object()
	{
		return get_object(getContext());
	}

	/**
	 * @param context
	 * @return value of _object
	 */
	public final java.lang.String get_object(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._object.toString());
	}

	/**
	 * Set value of _object
	 * @param _object
	 */
	public final void set_object(java.lang.String _object)
	{
		set_object(getContext(), _object);
	}

	/**
	 * Set value of _object
	 * @param context
	 * @param _object
	 */
	public final void set_object(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _object)
	{
		getMendixObject().setValue(context, MemberNames._object.toString(), _object);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode()
	{
		return getLivemode(getContext());
	}

	/**
	 * @param context
	 * @return value of Livemode
	 */
	public final java.lang.Boolean getLivemode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Livemode.toString());
	}

	/**
	 * Set value of Livemode
	 * @param livemode
	 */
	public final void setLivemode(java.lang.Boolean livemode)
	{
		setLivemode(getContext(), livemode);
	}

	/**
	 * Set value of Livemode
	 * @param context
	 * @param livemode
	 */
	public final void setLivemode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean livemode)
	{
		getMendixObject().setValue(context, MemberNames.Livemode.toString(), livemode);
	}

	/**
	 * @return value of Product
	 */
	public final java.lang.String getProduct()
	{
		return getProduct(getContext());
	}

	/**
	 * @param context
	 * @return value of Product
	 */
	public final java.lang.String getProduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Product.toString());
	}

	/**
	 * Set value of Product
	 * @param product
	 */
	public final void setProduct(java.lang.String product)
	{
		setProduct(getContext(), product);
	}

	/**
	 * Set value of Product
	 * @param context
	 * @param product
	 */
	public final void setProduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.Product.toString(), product);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Unit_Amount_String
	 */
	public final java.lang.String getUnit_Amount_String()
	{
		return getUnit_Amount_String(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_Amount_String
	 */
	public final java.lang.String getUnit_Amount_String(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Unit_Amount_String.toString());
	}

	/**
	 * Set value of Unit_Amount_String
	 * @param unit_amount_string
	 */
	public final void setUnit_Amount_String(java.lang.String unit_amount_string)
	{
		setUnit_Amount_String(getContext(), unit_amount_string);
	}

	/**
	 * Set value of Unit_Amount_String
	 * @param context
	 * @param unit_amount_string
	 */
	public final void setUnit_Amount_String(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unit_amount_string)
	{
		getMendixObject().setValue(context, MemberNames.Unit_Amount_String.toString(), unit_amount_string);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return priceAPIMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final paymentgatewaystripe.proxies.PriceAPI that = (paymentgatewaystripe.proxies.PriceAPI) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
