// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package paymentgatewaystripe.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the PaymentGatewayStripe module
	public static void aCT_AddExpand(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.ACT_AddExpand").withParams(params).execute(context);
	}
	public static void aCT_AddTires(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.ACT_AddTires").withParams(params).execute(context);
	}
	public static java.lang.String aCT_DecrptStripeSecretKey(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.ACT_DecrptStripeSecretKey").withParams(params).execute(context);
	}
	public static void aCT_GeneratePrice_Stripe(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.ACT_GeneratePrice_Stripe").withParams(params).execute(context);
	}
	public static void aCT_InvoicePaid(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.ACT_InvoicePaid").withParams(params).execute(context);
	}
	public static void aCT_SaveStripeConfiguration(IContext context, paymentgatewaystripe.proxies.StripeConfiguration _stripeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("StripeConfiguration", _stripeConfiguration == null ? null : _stripeConfiguration.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.ACT_SaveStripeConfiguration").withParams(params).execute(context);
	}
	public static java.lang.String sUB_CreatePrice(IContext context, java.lang.String _body, java.lang.String _secretKey, java.lang.String _baseURL)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Body", _body);
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_CreatePrice").withParams(params).execute(context);
	}
	public static java.lang.String sUB_FinalizeInvoice(IContext context, java.lang.String _secretKey, java.lang.String _baseURL, java.lang.String _body, java.lang.String _invoiceID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		params.put("Body", _body);
		params.put("InvoiceID", _invoiceID);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_FinalizeInvoice").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Generate_FormURLEncoded(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_Generate_FormURLEncoded").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GenerateExpand(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GenerateExpand").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GenerateInvoice(IContext context, java.lang.String _secretKey, java.lang.String _baseURL, java.lang.String _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		params.put("Body", _body);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GenerateInvoice").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GenerateInvoiceLineItems(IContext context, java.lang.String _secretKey, java.lang.String _baseURL, java.lang.String _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		params.put("Body", _body);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GenerateInvoiceLineItems").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GenerateNewProduct(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GenerateNewProduct").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GeneratePaymentLink(IContext context, java.lang.String _secretKey, java.lang.String _baseURL, java.lang.String _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		params.put("Body", _body);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GeneratePaymentLink").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GenerateTiers(IContext context, paymentgatewaystripe.proxies.PriceAPI _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_GenerateTiers").withParams(params).execute(context);
	}
	public static void sUB_GetProductList(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("PaymentGatewayStripe.SUB_GetProductList").withParams(params).execute(context);
	}
	public static void sUB_Invoice(IContext context, paymentgatewaystripe.proxies.Helper _helper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Helper", _helper == null ? null : _helper.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.SUB_Invoice").withParams(params).execute(context);
	}
	public static java.lang.String sUB_ListProducts(IContext context, java.lang.String _secretKey, java.lang.String _baseURL)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SecretKey", _secretKey);
		params.put("BaseURL", _baseURL);
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_ListProducts").withParams(params).execute(context);
	}
	public static void sUB_PaymentLink(IContext context, paymentgatewaystripe.proxies.Helper _helper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Helper", _helper == null ? null : _helper.getMendixObject());
		Core.microflowCall("PaymentGatewayStripe.SUB_PaymentLink").withParams(params).execute(context);
	}
	public static java.lang.String sUB_PaymentLink_Donate(IContext context, paymentgatewaystripe.proxies.Helper _helper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Helper", _helper == null ? null : _helper.getMendixObject());
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_PaymentLink_Donate").withParams(params).execute(context);
	}
	public static java.lang.String sUB_PaymentLink_Donate_QR(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("PaymentGatewayStripe.SUB_PaymentLink_Donate_QR").withParams(params).execute(context);
	}
}
